package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Barrio generated by hbm2java
 */
public class Barrio  implements java.io.Serializable {


     private Integer id;
     private Localidad localidad;
     private Viajante viajante;
     private String nombre;
     private Set domicilios = new HashSet(0);

    public Barrio() {
    }

	
    public Barrio(Localidad localidad, String nombre) {
        this.localidad = localidad;
        this.nombre = nombre;
    }
    public Barrio(Localidad localidad, Viajante viajante, String nombre, Set domicilios) {
       this.localidad = localidad;
       this.viajante = viajante;
       this.nombre = nombre;
       this.domicilios = domicilios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public Viajante getViajante() {
        return this.viajante;
    }
    
    public void setViajante(Viajante viajante) {
        this.viajante = viajante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set domicilios) {
        this.domicilios = domicilios;
    }




}


