package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cobroefectivo generated by hbm2java
 */
@Entity
@Table(name="cobroefectivo"
    ,catalog="seee"
)
public class Cobroefectivo  implements java.io.Serializable {


     private int idDetalleCobroPedido;
     private Detallecobropedido detallecobropedido;

    public Cobroefectivo() {
    }

    public Cobroefectivo(int idDetalleCobroPedido, Detallecobropedido detallecobropedido) {
       this.idDetalleCobroPedido = idDetalleCobroPedido;
       this.detallecobropedido = detallecobropedido;
    }
   
     @Id 
    
    @Column(name="idDetalleCobroPedido", unique=true, nullable=false)
    public int getIdDetalleCobroPedido() {
        return this.idDetalleCobroPedido;
    }
    
    public void setIdDetalleCobroPedido(int idDetalleCobroPedido) {
        this.idDetalleCobroPedido = idDetalleCobroPedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDetalleCobroPedido", unique=true, nullable=false, insertable=false, updatable=false)
    public Detallecobropedido getDetallecobropedido() {
        return this.detallecobropedido;
    }
    
    public void setDetallecobropedido(Detallecobropedido detallecobropedido) {
        this.detallecobropedido = detallecobropedido;
    }




}


