package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Cobrocheque generated by hbm2java
 */
public class Cobrocheque  implements java.io.Serializable {


     private int idDetalleCobroPedido;
     private Estadocobrocheque estadocobrocheque;
     private Detallecobropedido detallecobropedido;
     private Cheque cheque;

    public Cobrocheque() {
    }

    public Cobrocheque(int idDetalleCobroPedido, Estadocobrocheque estadocobrocheque, Detallecobropedido detallecobropedido, Cheque cheque) {
       this.idDetalleCobroPedido = idDetalleCobroPedido;
       this.estadocobrocheque = estadocobrocheque;
       this.detallecobropedido = detallecobropedido;
       this.cheque = cheque;
    }
   
    public int getIdDetalleCobroPedido() {
        return this.idDetalleCobroPedido;
    }
    
    public void setIdDetalleCobroPedido(int idDetalleCobroPedido) {
        this.idDetalleCobroPedido = idDetalleCobroPedido;
    }
    public Estadocobrocheque getEstadocobrocheque() {
        return this.estadocobrocheque;
    }
    
    public void setEstadocobrocheque(Estadocobrocheque estadocobrocheque) {
        this.estadocobrocheque = estadocobrocheque;
    }
    public Detallecobropedido getDetallecobropedido() {
        return this.detallecobropedido;
    }
    
    public void setDetallecobropedido(Detallecobropedido detallecobropedido) {
        this.detallecobropedido = detallecobropedido;
    }
    public Cheque getCheque() {
        return this.cheque;
    }
    
    public void setCheque(Cheque cheque) {
        this.cheque = cheque;
    }




}


