package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cobropedido generated by hbm2java
 */
@Entity
@Table(name="cobropedido"
    ,catalog="seee"
)
public class Cobropedido  implements java.io.Serializable {


     private Integer id;
     private Estadocobropedido estadocobropedido;
     private Date fechaCobro;
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Detallecobropedido> detallecobropedidos = new HashSet<Detallecobropedido>(0);

    public Cobropedido() {
    }

	
    public Cobropedido(Estadocobropedido estadocobropedido, Date fechaCobro) {
        this.estadocobropedido = estadocobropedido;
        this.fechaCobro = fechaCobro;
    }
    public Cobropedido(Estadocobropedido estadocobropedido, Date fechaCobro, Set<Venta> ventas, Set<Detallecobropedido> detallecobropedidos) {
       this.estadocobropedido = estadocobropedido;
       this.fechaCobro = fechaCobro;
       this.ventas = ventas;
       this.detallecobropedidos = detallecobropedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoCobroPedido", nullable=false)
    public Estadocobropedido getEstadocobropedido() {
        return this.estadocobropedido;
    }
    
    public void setEstadocobropedido(Estadocobropedido estadocobropedido) {
        this.estadocobropedido = estadocobropedido;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaCobro", nullable=false, length=10)
    public Date getFechaCobro() {
        return this.fechaCobro;
    }
    
    public void setFechaCobro(Date fechaCobro) {
        this.fechaCobro = fechaCobro;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cobropedido")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cobropedido")
    public Set<Detallecobropedido> getDetallecobropedidos() {
        return this.detallecobropedidos;
    }
    
    public void setDetallecobropedidos(Set<Detallecobropedido> detallecobropedidos) {
        this.detallecobropedidos = detallecobropedidos;
    }




}


