package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set productoterminados = new HashSet(0);

    public Color() {
    }

	
    public Color(String nombre) {
        this.nombre = nombre;
    }
    public Color(String nombre, Set productoterminados) {
       this.nombre = nombre;
       this.productoterminados = productoterminados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoterminados() {
        return this.productoterminados;
    }
    
    public void setProductoterminados(Set productoterminados) {
        this.productoterminados = productoterminados;
    }




}


