package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="seee"
)
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Date fechaRealLlegada;
     private Set<Productosdefectuososxcompra> productosdefectuososxcompras = new HashSet<Productosdefectuososxcompra>(0);
     private Set<Importacion> importacions = new HashSet<Importacion>(0);
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Compra() {
    }

    public Compra(Date fechaRealLlegada, Set<Productosdefectuososxcompra> productosdefectuososxcompras, Set<Importacion> importacions, Set<Detallecompra> detallecompras) {
       this.fechaRealLlegada = fechaRealLlegada;
       this.productosdefectuososxcompras = productosdefectuososxcompras;
       this.importacions = importacions;
       this.detallecompras = detallecompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaRealLlegada", length=10)
    public Date getFechaRealLlegada() {
        return this.fechaRealLlegada;
    }
    
    public void setFechaRealLlegada(Date fechaRealLlegada) {
        this.fechaRealLlegada = fechaRealLlegada;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compra")
    public Set<Productosdefectuososxcompra> getProductosdefectuososxcompras() {
        return this.productosdefectuososxcompras;
    }
    
    public void setProductosdefectuososxcompras(Set<Productosdefectuososxcompra> productosdefectuososxcompras) {
        this.productosdefectuososxcompras = productosdefectuososxcompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compra")
    public Set<Importacion> getImportacions() {
        return this.importacions;
    }
    
    public void setImportacions(Set<Importacion> importacions) {
        this.importacions = importacions;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compra")
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }




}


