package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Condicioniva generated by hbm2java
 */
@Entity
@Table(name="condicioniva"
    ,catalog="seee"
)
public class Condicioniva  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set<Empresacliente> empresaclientes = new HashSet<Empresacliente>(0);

    public Condicioniva() {
    }

	
    public Condicioniva(String nombre) {
        this.nombre = nombre;
    }
    public Condicioniva(String nombre, String descripcion, Set<Empresacliente> empresaclientes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empresaclientes = empresaclientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="condicioniva")
    public Set<Empresacliente> getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set<Empresacliente> empresaclientes) {
        this.empresaclientes = empresaclientes;
    }




}


