package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecompra generated by hbm2java
 */
@Entity
@Table(name="detallecompra"
    ,catalog="seee"
)
public class Detallecompra  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Detalleordencompra detalleordencompra;
     private Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados = new HashSet<Detalleordencompraproductoimportado>(0);
     private Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas = new HashSet<Detalleordencompramateriaprima>(0);

    public Detallecompra() {
    }

	
    public Detallecompra(Compra compra, Detalleordencompra detalleordencompra) {
        this.compra = compra;
        this.detalleordencompra = detalleordencompra;
    }
    public Detallecompra(Compra compra, Detalleordencompra detalleordencompra, Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados, Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas) {
       this.compra = compra;
       this.detalleordencompra = detalleordencompra;
       this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
       this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCompra", nullable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDetalleOrdenCompra", nullable=false)
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="detallecompraproductoimportado", catalog="seee", joinColumns = { 
        @JoinColumn(name="idDetalleCompra", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idDetalleOrdenCompraProductoImportado", nullable=false, updatable=false) })
    public Set<Detalleordencompraproductoimportado> getDetalleordencompraproductoimportados() {
        return this.detalleordencompraproductoimportados;
    }
    
    public void setDetalleordencompraproductoimportados(Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados) {
        this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="detallecompramateriaprima", catalog="seee", joinColumns = { 
        @JoinColumn(name="idDetalleCompra", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idDetalleOrdenCompraMateriaPrima", nullable=false, updatable=false) })
    public Set<Detalleordencompramateriaprima> getDetalleordencompramateriaprimas() {
        return this.detalleordencompramateriaprimas;
    }
    
    public void setDetalleordencompramateriaprimas(Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas) {
        this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }




}


