package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detallecobropedido generated by hbm2java
 */
public class Detallecobropedido  implements java.io.Serializable {


     private Integer id;
     private Cobropedido cobropedido;
     private float varlor;
     private Date fecha;
     private Set cobroefectivos = new HashSet(0);
     private Set cobrocheques = new HashSet(0);
     private Set creditoclientes = new HashSet(0);

    public Detallecobropedido() {
    }

	
    public Detallecobropedido(Cobropedido cobropedido, float varlor, Date fecha) {
        this.cobropedido = cobropedido;
        this.varlor = varlor;
        this.fecha = fecha;
    }
    public Detallecobropedido(Cobropedido cobropedido, float varlor, Date fecha, Set cobroefectivos, Set cobrocheques, Set creditoclientes) {
       this.cobropedido = cobropedido;
       this.varlor = varlor;
       this.fecha = fecha;
       this.cobroefectivos = cobroefectivos;
       this.cobrocheques = cobrocheques;
       this.creditoclientes = creditoclientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cobropedido getCobropedido() {
        return this.cobropedido;
    }
    
    public void setCobropedido(Cobropedido cobropedido) {
        this.cobropedido = cobropedido;
    }
    public float getVarlor() {
        return this.varlor;
    }
    
    public void setVarlor(float varlor) {
        this.varlor = varlor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCobroefectivos() {
        return this.cobroefectivos;
    }
    
    public void setCobroefectivos(Set cobroefectivos) {
        this.cobroefectivos = cobroefectivos;
    }
    public Set getCobrocheques() {
        return this.cobrocheques;
    }
    
    public void setCobrocheques(Set cobrocheques) {
        this.cobrocheques = cobrocheques;
    }
    public Set getCreditoclientes() {
        return this.creditoclientes;
    }
    
    public void setCreditoclientes(Set creditoclientes) {
        this.creditoclientes = creditoclientes;
    }




}


