package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private Integer id;
     private Venta venta;
     private Productoterminado productoterminado;
     private Estadodetalleventa estadodetalleventa;
     private int cantidadProducto;
     private float precioUnidad;
     private String motivoDevolucion;
     private Date fechaDevolucion;
     private Set detalledevolucionproductosterminadoses = new HashSet(0);

    public Detalleventa() {
    }

	
    public Detalleventa(Venta venta, Productoterminado productoterminado, Estadodetalleventa estadodetalleventa, int cantidadProducto, float precioUnidad) {
        this.venta = venta;
        this.productoterminado = productoterminado;
        this.estadodetalleventa = estadodetalleventa;
        this.cantidadProducto = cantidadProducto;
        this.precioUnidad = precioUnidad;
    }
    public Detalleventa(Venta venta, Productoterminado productoterminado, Estadodetalleventa estadodetalleventa, int cantidadProducto, float precioUnidad, String motivoDevolucion, Date fechaDevolucion, Set detalledevolucionproductosterminadoses) {
       this.venta = venta;
       this.productoterminado = productoterminado;
       this.estadodetalleventa = estadodetalleventa;
       this.cantidadProducto = cantidadProducto;
       this.precioUnidad = precioUnidad;
       this.motivoDevolucion = motivoDevolucion;
       this.fechaDevolucion = fechaDevolucion;
       this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
    public Estadodetalleventa getEstadodetalleventa() {
        return this.estadodetalleventa;
    }
    
    public void setEstadodetalleventa(Estadodetalleventa estadodetalleventa) {
        this.estadodetalleventa = estadodetalleventa;
    }
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public float getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(float precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public String getMotivoDevolucion() {
        return this.motivoDevolucion;
    }
    
    public void setMotivoDevolucion(String motivoDevolucion) {
        this.motivoDevolucion = motivoDevolucion;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Set getDetalledevolucionproductosterminadoses() {
        return this.detalledevolucionproductosterminadoses;
    }
    
    public void setDetalledevolucionproductosterminadoses(Set detalledevolucionproductosterminadoses) {
        this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }




}


