package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallenotificacionreaprovisionamiento generated by hbm2java
 */
@Entity
@Table(name="detallenotificacionreaprovisionamiento"
    ,catalog="seee"
)
public class Detallenotificacionreaprovisionamiento  implements java.io.Serializable {


     private Integer id;
     private Productoimportado productoimportado;
     private Notificacionreaprovisionamiento notificacionreaprovisionamiento;
     private int cantidad;

    public Detallenotificacionreaprovisionamiento() {
    }

    public Detallenotificacionreaprovisionamiento(Productoimportado productoimportado, Notificacionreaprovisionamiento notificacionreaprovisionamiento, int cantidad) {
       this.productoimportado = productoimportado;
       this.notificacionreaprovisionamiento = notificacionreaprovisionamiento;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProductoImportado", nullable=false)
    public Productoimportado getProductoimportado() {
        return this.productoimportado;
    }
    
    public void setProductoimportado(Productoimportado productoimportado) {
        this.productoimportado = productoimportado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idNotificacionReaprovisionamiento", nullable=false)
    public Notificacionreaprovisionamiento getNotificacionreaprovisionamiento() {
        return this.notificacionreaprovisionamiento;
    }
    
    public void setNotificacionreaprovisionamiento(Notificacionreaprovisionamiento notificacionreaprovisionamiento) {
        this.notificacionreaprovisionamiento = notificacionreaprovisionamiento;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


