package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Detallenotificacionreaprovisionamiento generated by hbm2java
 */
public class Detallenotificacionreaprovisionamiento  implements java.io.Serializable {


     private Integer id;
     private Productoimportado productoimportado;
     private Notificacionreaprovisionamiento notificacionreaprovisionamiento;
     private int cantidad;

    public Detallenotificacionreaprovisionamiento() {
    }

    public Detallenotificacionreaprovisionamiento(Productoimportado productoimportado, Notificacionreaprovisionamiento notificacionreaprovisionamiento, int cantidad) {
       this.productoimportado = productoimportado;
       this.notificacionreaprovisionamiento = notificacionreaprovisionamiento;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Productoimportado getProductoimportado() {
        return this.productoimportado;
    }
    
    public void setProductoimportado(Productoimportado productoimportado) {
        this.productoimportado = productoimportado;
    }
    public Notificacionreaprovisionamiento getNotificacionreaprovisionamiento() {
        return this.notificacionreaprovisionamiento;
    }
    
    public void setNotificacionreaprovisionamiento(Notificacionreaprovisionamiento notificacionreaprovisionamiento) {
        this.notificacionreaprovisionamiento = notificacionreaprovisionamiento;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


