package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Detalleordencompra generated by hbm2java
 */
public class Detalleordencompra  implements java.io.Serializable {


     private Integer id;
     private Estadodetalleordencompra estadodetalleordencompra;
     private float precio;
     private Set detallecompras = new HashSet(0);
     private Set detalleordencompraproductoimportados = new HashSet(0);
     private Set detalleordencompramateriaprimas = new HashSet(0);

    public Detalleordencompra() {
    }

	
    public Detalleordencompra(Estadodetalleordencompra estadodetalleordencompra, float precio) {
        this.estadodetalleordencompra = estadodetalleordencompra;
        this.precio = precio;
    }
    public Detalleordencompra(Estadodetalleordencompra estadodetalleordencompra, float precio, Set detallecompras, Set detalleordencompraproductoimportados, Set detalleordencompramateriaprimas) {
       this.estadodetalleordencompra = estadodetalleordencompra;
       this.precio = precio;
       this.detallecompras = detallecompras;
       this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
       this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estadodetalleordencompra getEstadodetalleordencompra() {
        return this.estadodetalleordencompra;
    }
    
    public void setEstadodetalleordencompra(Estadodetalleordencompra estadodetalleordencompra) {
        this.estadodetalleordencompra = estadodetalleordencompra;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }
    public Set getDetalleordencompraproductoimportados() {
        return this.detalleordencompraproductoimportados;
    }
    
    public void setDetalleordencompraproductoimportados(Set detalleordencompraproductoimportados) {
        this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }
    public Set getDetalleordencompramateriaprimas() {
        return this.detalleordencompramateriaprimas;
    }
    
    public void setDetalleordencompramateriaprimas(Set detalleordencompramateriaprimas) {
        this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }




}


