package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Detalleordencompra generated by hbm2java
 */
@Entity
@Table(name="detalleordencompra"
    ,catalog="seee"
)
public class Detalleordencompra  implements java.io.Serializable {


     private Integer id;
     private Estadodetalleordencompra estadodetalleordencompra;
     private float precio;
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);
     private Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados = new HashSet<Detalleordencompraproductoimportado>(0);
     private Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas = new HashSet<Detalleordencompramateriaprima>(0);

    public Detalleordencompra() {
    }

	
    public Detalleordencompra(Estadodetalleordencompra estadodetalleordencompra, float precio) {
        this.estadodetalleordencompra = estadodetalleordencompra;
        this.precio = precio;
    }
    public Detalleordencompra(Estadodetalleordencompra estadodetalleordencompra, float precio, Set<Detallecompra> detallecompras, Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados, Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas) {
       this.estadodetalleordencompra = estadodetalleordencompra;
       this.precio = precio;
       this.detallecompras = detallecompras;
       this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
       this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoDetalleOrdenCompra", nullable=false)
    public Estadodetalleordencompra getEstadodetalleordencompra() {
        return this.estadodetalleordencompra;
    }
    
    public void setEstadodetalleordencompra(Estadodetalleordencompra estadodetalleordencompra) {
        this.estadodetalleordencompra = estadodetalleordencompra;
    }
    
    @Column(name="precio", nullable=false, precision=9)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleordencompra")
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleordencompra")
    public Set<Detalleordencompraproductoimportado> getDetalleordencompraproductoimportados() {
        return this.detalleordencompraproductoimportados;
    }
    
    public void setDetalleordencompraproductoimportados(Set<Detalleordencompraproductoimportado> detalleordencompraproductoimportados) {
        this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleordencompra")
    public Set<Detalleordencompramateriaprima> getDetalleordencompramateriaprimas() {
        return this.detalleordencompramateriaprimas;
    }
    
    public void setDetalleordencompramateriaprimas(Set<Detalleordencompramateriaprima> detalleordencompramateriaprimas) {
        this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }




}


