package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallemateriaprima generated by hbm2java
 */
@Entity
@Table(name="detallemateriaprima"
    ,catalog="seee"
)
public class Detallemateriaprima  implements java.io.Serializable {


     private Integer id;
     private Lote lote;
     private Materiaprima materiaprima;
     private int cantidadMateriaPrima;

    public Detallemateriaprima() {
    }

    public Detallemateriaprima(Lote lote, Materiaprima materiaprima, int cantidadMateriaPrima) {
       this.lote = lote;
       this.materiaprima = materiaprima;
       this.cantidadMateriaPrima = cantidadMateriaPrima;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLote", nullable=false)
    public Lote getLote() {
        return this.lote;
    }
    
    public void setLote(Lote lote) {
        this.lote = lote;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMateriaPrima", nullable=false)
    public Materiaprima getMateriaprima() {
        return this.materiaprima;
    }
    
    public void setMateriaprima(Materiaprima materiaprima) {
        this.materiaprima = materiaprima;
    }
    
    @Column(name="cantidadMateriaPrima", nullable=false)
    public int getCantidadMateriaPrima() {
        return this.cantidadMateriaPrima;
    }
    
    public void setCantidadMateriaPrima(int cantidadMateriaPrima) {
        this.cantidadMateriaPrima = cantidadMateriaPrima;
    }




}


