package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleordencompraproductoimportado generated by hbm2java
 */
@Entity
@Table(name="detalleordencompraproductoimportado"
    ,catalog="seee"
)
public class Detalleordencompraproductoimportado  implements java.io.Serializable {


     private int idDetalleOrdenCompra;
     private Productoimportado productoimportado;
     private Detalleordencompra detalleordencompra;
     private int cantidadProducto;
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Detalleordencompraproductoimportado() {
    }

	
    public Detalleordencompraproductoimportado(int idDetalleOrdenCompra, Productoimportado productoimportado, Detalleordencompra detalleordencompra, int cantidadProducto) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
        this.productoimportado = productoimportado;
        this.detalleordencompra = detalleordencompra;
        this.cantidadProducto = cantidadProducto;
    }
    public Detalleordencompraproductoimportado(int idDetalleOrdenCompra, Productoimportado productoimportado, Detalleordencompra detalleordencompra, int cantidadProducto, Set<Detallecompra> detallecompras) {
       this.idDetalleOrdenCompra = idDetalleOrdenCompra;
       this.productoimportado = productoimportado;
       this.detalleordencompra = detalleordencompra;
       this.cantidadProducto = cantidadProducto;
       this.detallecompras = detallecompras;
    }
   
     @Id 
    
    @Column(name="idDetalleOrdenCompra", unique=true, nullable=false)
    public int getIdDetalleOrdenCompra() {
        return this.idDetalleOrdenCompra;
    }
    
    public void setIdDetalleOrdenCompra(int idDetalleOrdenCompra) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProductoImportado", nullable=false)
    public Productoimportado getProductoimportado() {
        return this.productoimportado;
    }
    
    public void setProductoimportado(Productoimportado productoimportado) {
        this.productoimportado = productoimportado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDetalleOrdenCompra", unique=true, nullable=false, insertable=false, updatable=false)
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
    
    @Column(name="cantidadProducto", nullable=false)
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="detallecompraproductoimportado", catalog="seee", joinColumns = { 
        @JoinColumn(name="idDetalleOrdenCompraProductoImportado", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idDetalleCompra", unique=true, nullable=false, updatable=false) })
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }




}


