package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallecobropedido generated by hbm2java
 */
@Entity
@Table(name="detallecobropedido"
    ,catalog="seee"
)
public class Detallecobropedido  implements java.io.Serializable {


     private Integer id;
     private Cobropedido cobropedido;
     private float varlor;
     private Date fecha;
     private Set<Cobroefectivo> cobroefectivos = new HashSet<Cobroefectivo>(0);
     private Set<Cobrocheque> cobrocheques = new HashSet<Cobrocheque>(0);
     private Set<Creditocliente> creditoclientes = new HashSet<Creditocliente>(0);

    public Detallecobropedido() {
    }

	
    public Detallecobropedido(Cobropedido cobropedido, float varlor, Date fecha) {
        this.cobropedido = cobropedido;
        this.varlor = varlor;
        this.fecha = fecha;
    }
    public Detallecobropedido(Cobropedido cobropedido, float varlor, Date fecha, Set<Cobroefectivo> cobroefectivos, Set<Cobrocheque> cobrocheques, Set<Creditocliente> creditoclientes) {
       this.cobropedido = cobropedido;
       this.varlor = varlor;
       this.fecha = fecha;
       this.cobroefectivos = cobroefectivos;
       this.cobrocheques = cobrocheques;
       this.creditoclientes = creditoclientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCobroPedido", nullable=false)
    public Cobropedido getCobropedido() {
        return this.cobropedido;
    }
    
    public void setCobropedido(Cobropedido cobropedido) {
        this.cobropedido = cobropedido;
    }
    
    @Column(name="varlor", nullable=false, precision=9)
    public float getVarlor() {
        return this.varlor;
    }
    
    public void setVarlor(float varlor) {
        this.varlor = varlor;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detallecobropedido")
    public Set<Cobroefectivo> getCobroefectivos() {
        return this.cobroefectivos;
    }
    
    public void setCobroefectivos(Set<Cobroefectivo> cobroefectivos) {
        this.cobroefectivos = cobroefectivos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detallecobropedido")
    public Set<Cobrocheque> getCobrocheques() {
        return this.cobrocheques;
    }
    
    public void setCobrocheques(Set<Cobrocheque> cobrocheques) {
        this.cobrocheques = cobrocheques;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="cobronotacredito", catalog="seee", joinColumns = { 
        @JoinColumn(name="idDetalleCobroPedido", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idCreditoCliente", nullable=false, updatable=false) })
    public Set<Creditocliente> getCreditoclientes() {
        return this.creditoclientes;
    }
    
    public void setCreditoclientes(Set<Creditocliente> creditoclientes) {
        this.creditoclientes = creditoclientes;
    }




}


