package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Detalleordencompra detalleordencompra;
     private Set detalleordencompraproductoimportados = new HashSet(0);
     private Set detalleordencompramateriaprimas = new HashSet(0);

    public Detallecompra() {
    }

	
    public Detallecompra(Compra compra, Detalleordencompra detalleordencompra) {
        this.compra = compra;
        this.detalleordencompra = detalleordencompra;
    }
    public Detallecompra(Compra compra, Detalleordencompra detalleordencompra, Set detalleordencompraproductoimportados, Set detalleordencompramateriaprimas) {
       this.compra = compra;
       this.detalleordencompra = detalleordencompra;
       this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
       this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
    public Set getDetalleordencompraproductoimportados() {
        return this.detalleordencompraproductoimportados;
    }
    
    public void setDetalleordencompraproductoimportados(Set detalleordencompraproductoimportados) {
        this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }
    public Set getDetalleordencompramateriaprimas() {
        return this.detalleordencompramateriaprimas;
    }
    
    public void setDetalleordencompramateriaprimas(Set detalleordencompramateriaprimas) {
        this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }




}


