package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detalleventa generated by hbm2java
 */
@Entity
@Table(name="detalleventa"
    ,catalog="seee"
)
public class Detalleventa  implements java.io.Serializable {


     private Integer id;
     private Venta venta;
     private Productoterminado productoterminado;
     private Estadodetalleventa estadodetalleventa;
     private int cantidadProducto;
     private float precioUnidad;
     private String motivoDevolucion;
     private Date fechaDevolucion;
     private Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses = new HashSet<Detalledevolucionproductosterminados>(0);

    public Detalleventa() {
    }

	
    public Detalleventa(Venta venta, Productoterminado productoterminado, Estadodetalleventa estadodetalleventa, int cantidadProducto, float precioUnidad) {
        this.venta = venta;
        this.productoterminado = productoterminado;
        this.estadodetalleventa = estadodetalleventa;
        this.cantidadProducto = cantidadProducto;
        this.precioUnidad = precioUnidad;
    }
    public Detalleventa(Venta venta, Productoterminado productoterminado, Estadodetalleventa estadodetalleventa, int cantidadProducto, float precioUnidad, String motivoDevolucion, Date fechaDevolucion, Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses) {
       this.venta = venta;
       this.productoterminado = productoterminado;
       this.estadodetalleventa = estadodetalleventa;
       this.cantidadProducto = cantidadProducto;
       this.precioUnidad = precioUnidad;
       this.motivoDevolucion = motivoDevolucion;
       this.fechaDevolucion = fechaDevolucion;
       this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVenta", nullable=false)
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoDetalleVenta", nullable=false)
    public Estadodetalleventa getEstadodetalleventa() {
        return this.estadodetalleventa;
    }
    
    public void setEstadodetalleventa(Estadodetalleventa estadodetalleventa) {
        this.estadodetalleventa = estadodetalleventa;
    }
    
    @Column(name="cantidadProducto", nullable=false)
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    
    @Column(name="precioUnidad", nullable=false, precision=9)
    public float getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(float precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    
    @Column(name="motivoDevolucion", length=200)
    public String getMotivoDevolucion() {
        return this.motivoDevolucion;
    }
    
    public void setMotivoDevolucion(String motivoDevolucion) {
        this.motivoDevolucion = motivoDevolucion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaDevolucion", length=10)
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detalleventa")
    public Set<Detalledevolucionproductosterminados> getDetalledevolucionproductosterminadoses() {
        return this.detalledevolucionproductosterminadoses;
    }
    
    public void setDetalledevolucionproductosterminadoses(Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses) {
        this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }




}


