package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Detallepedidoproductosterminados generated by hbm2java
 */
@Entity
@Table(name="detallepedidoproductosterminados"
    ,catalog="seee"
)
public class Detallepedidoproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Productoterminado productoterminado;
     private Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado;
     private Pedidoproductosterminados pedidoproductosterminados;
     private int cantidadProducto;
     private float precioPorUnidad;
     private String motivoDevolucion;
     private String motivoNoEntregado;
     private Integer fechaDevolucion;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);

    public Detallepedidoproductosterminados() {
    }

	
    public Detallepedidoproductosterminados(Productoterminado productoterminado, Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado, Pedidoproductosterminados pedidoproductosterminados, int cantidadProducto, float precioPorUnidad) {
        this.productoterminado = productoterminado;
        this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
        this.pedidoproductosterminados = pedidoproductosterminados;
        this.cantidadProducto = cantidadProducto;
        this.precioPorUnidad = precioPorUnidad;
    }
    public Detallepedidoproductosterminados(Productoterminado productoterminado, Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado, Pedidoproductosterminados pedidoproductosterminados, int cantidadProducto, float precioPorUnidad, String motivoDevolucion, String motivoNoEntregado, Integer fechaDevolucion, Set<Detallefactura> detallefacturas) {
       this.productoterminado = productoterminado;
       this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
       this.pedidoproductosterminados = pedidoproductosterminados;
       this.cantidadProducto = cantidadProducto;
       this.precioPorUnidad = precioPorUnidad;
       this.motivoDevolucion = motivoDevolucion;
       this.motivoNoEntregado = motivoNoEntregado;
       this.fechaDevolucion = fechaDevolucion;
       this.detallefacturas = detallefacturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProductoTerminado", nullable=false)
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoDetallePedidoProductoTerminado", nullable=false)
    public Estadodetallepedidoproductoterminado getEstadodetallepedidoproductoterminado() {
        return this.estadodetallepedidoproductoterminado;
    }
    
    public void setEstadodetallepedidoproductoterminado(Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado) {
        this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPedidoProductosTerminados", nullable=false)
    public Pedidoproductosterminados getPedidoproductosterminados() {
        return this.pedidoproductosterminados;
    }
    
    public void setPedidoproductosterminados(Pedidoproductosterminados pedidoproductosterminados) {
        this.pedidoproductosterminados = pedidoproductosterminados;
    }
    
    @Column(name="cantidadProducto", nullable=false)
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    
    @Column(name="precioPorUnidad", nullable=false, precision=9)
    public float getPrecioPorUnidad() {
        return this.precioPorUnidad;
    }
    
    public void setPrecioPorUnidad(float precioPorUnidad) {
        this.precioPorUnidad = precioPorUnidad;
    }
    
    @Column(name="motivoDevolucion", length=100)
    public String getMotivoDevolucion() {
        return this.motivoDevolucion;
    }
    
    public void setMotivoDevolucion(String motivoDevolucion) {
        this.motivoDevolucion = motivoDevolucion;
    }
    
    @Column(name="motivoNoEntregado", length=100)
    public String getMotivoNoEntregado() {
        return this.motivoNoEntregado;
    }
    
    public void setMotivoNoEntregado(String motivoNoEntregado) {
        this.motivoNoEntregado = motivoNoEntregado;
    }
    
    @Column(name="fechaDevolucion")
    public Integer getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Integer fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detallepedidoproductosterminados")
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


