package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private Integer id;
     private Detallepedidoproductosterminados detallepedidoproductosterminados;
     private Factura factura;

    public Detallefactura() {
    }

	
    public Detallefactura(Factura factura) {
        this.factura = factura;
    }
    public Detallefactura(Detallepedidoproductosterminados detallepedidoproductosterminados, Factura factura) {
       this.detallepedidoproductosterminados = detallepedidoproductosterminados;
       this.factura = factura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Detallepedidoproductosterminados getDetallepedidoproductosterminados() {
        return this.detallepedidoproductosterminados;
    }
    
    public void setDetallepedidoproductosterminados(Detallepedidoproductosterminados detallepedidoproductosterminados) {
        this.detallepedidoproductosterminados = detallepedidoproductosterminados;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }




}


