package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detallecartera generated by hbm2java
 */
public class Detallecartera  implements java.io.Serializable {


     private Integer id;
     private Empresacliente empresacliente;
     private Estadocartera estadocartera;
     private Date fechaDesde;
     private Date fechaHasta;
     private Set viajantes = new HashSet(0);

    public Detallecartera() {
    }

	
    public Detallecartera(Empresacliente empresacliente, Estadocartera estadocartera, Date fechaDesde) {
        this.empresacliente = empresacliente;
        this.estadocartera = estadocartera;
        this.fechaDesde = fechaDesde;
    }
    public Detallecartera(Empresacliente empresacliente, Estadocartera estadocartera, Date fechaDesde, Date fechaHasta, Set viajantes) {
       this.empresacliente = empresacliente;
       this.estadocartera = estadocartera;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.viajantes = viajantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Estadocartera getEstadocartera() {
        return this.estadocartera;
    }
    
    public void setEstadocartera(Estadocartera estadocartera) {
        this.estadocartera = estadocartera;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public Set getViajantes() {
        return this.viajantes;
    }
    
    public void setViajantes(Set viajantes) {
        this.viajantes = viajantes;
    }




}


