package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Detalleordencompraproductoimportado generated by hbm2java
 */
public class Detalleordencompraproductoimportado  implements java.io.Serializable {


     private int idDetalleOrdenCompra;
     private Productoimportado productoimportado;
     private Detalleordencompra detalleordencompra;
     private int cantidadProducto;
     private Set detallecompras = new HashSet(0);

    public Detalleordencompraproductoimportado() {
    }

	
    public Detalleordencompraproductoimportado(int idDetalleOrdenCompra, Productoimportado productoimportado, Detalleordencompra detalleordencompra, int cantidadProducto) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
        this.productoimportado = productoimportado;
        this.detalleordencompra = detalleordencompra;
        this.cantidadProducto = cantidadProducto;
    }
    public Detalleordencompraproductoimportado(int idDetalleOrdenCompra, Productoimportado productoimportado, Detalleordencompra detalleordencompra, int cantidadProducto, Set detallecompras) {
       this.idDetalleOrdenCompra = idDetalleOrdenCompra;
       this.productoimportado = productoimportado;
       this.detalleordencompra = detalleordencompra;
       this.cantidadProducto = cantidadProducto;
       this.detallecompras = detallecompras;
    }
   
    public int getIdDetalleOrdenCompra() {
        return this.idDetalleOrdenCompra;
    }
    
    public void setIdDetalleOrdenCompra(int idDetalleOrdenCompra) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
    }
    public Productoimportado getProductoimportado() {
        return this.productoimportado;
    }
    
    public void setProductoimportado(Productoimportado productoimportado) {
        this.productoimportado = productoimportado;
    }
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


