package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devolucionproductosterminados generated by hbm2java
 */
@Entity
@Table(name="devolucionproductosterminados"
    ,catalog="seee"
)
public class Devolucionproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Empresacliente empresacliente;
     private Viajante viajante;
     private Date fecha;
     private Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses = new HashSet<Detalledevolucionproductosterminados>(0);

    public Devolucionproductosterminados() {
    }

	
    public Devolucionproductosterminados(Empresacliente empresacliente, Viajante viajante, Date fecha) {
        this.empresacliente = empresacliente;
        this.viajante = viajante;
        this.fecha = fecha;
    }
    public Devolucionproductosterminados(Empresacliente empresacliente, Viajante viajante, Date fecha, Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses) {
       this.empresacliente = empresacliente;
       this.viajante = viajante;
       this.fecha = fecha;
       this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idViajante", nullable=false)
    public Viajante getViajante() {
        return this.viajante;
    }
    
    public void setViajante(Viajante viajante) {
        this.viajante = viajante;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="devolucionproductosterminados")
    public Set<Detalledevolucionproductosterminados> getDetalledevolucionproductosterminadoses() {
        return this.detalledevolucionproductosterminadoses;
    }
    
    public void setDetalledevolucionproductosterminadoses(Set<Detalledevolucionproductosterminados> detalledevolucionproductosterminadoses) {
        this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }




}


