package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Devolucionproductosterminados generated by hbm2java
 */
public class Devolucionproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Empresacliente empresacliente;
     private Viajante viajante;
     private Date fecha;
     private Set detalledevolucionproductosterminadoses = new HashSet(0);

    public Devolucionproductosterminados() {
    }

	
    public Devolucionproductosterminados(Empresacliente empresacliente, Viajante viajante, Date fecha) {
        this.empresacliente = empresacliente;
        this.viajante = viajante;
        this.fecha = fecha;
    }
    public Devolucionproductosterminados(Empresacliente empresacliente, Viajante viajante, Date fecha, Set detalledevolucionproductosterminadoses) {
       this.empresacliente = empresacliente;
       this.viajante = viajante;
       this.fecha = fecha;
       this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Viajante getViajante() {
        return this.viajante;
    }
    
    public void setViajante(Viajante viajante) {
        this.viajante = viajante;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalledevolucionproductosterminadoses() {
        return this.detalledevolucionproductosterminadoses;
    }
    
    public void setDetalledevolucionproductosterminadoses(Set detalledevolucionproductosterminadoses) {
        this.detalledevolucionproductosterminadoses = detalledevolucionproductosterminadoses;
    }




}


