package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idPersona;
     private Cargo cargo;
     private Persona persona;
     private String cuil;
     private Date fechaIngreso;
     private Date fechaBaja;
     private String motivoBaja;
     private Set pedidoproductosterminadoses = new HashSet(0);
     private Set notificacionreaprovisionamientos = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int idPersona, Cargo cargo, Persona persona, String cuil, Date fechaIngreso) {
        this.idPersona = idPersona;
        this.cargo = cargo;
        this.persona = persona;
        this.cuil = cuil;
        this.fechaIngreso = fechaIngreso;
    }
    public Empleado(int idPersona, Cargo cargo, Persona persona, String cuil, Date fechaIngreso, Date fechaBaja, String motivoBaja, Set pedidoproductosterminadoses, Set notificacionreaprovisionamientos, Set pagos) {
       this.idPersona = idPersona;
       this.cargo = cargo;
       this.persona = persona;
       this.cuil = cuil;
       this.fechaIngreso = fechaIngreso;
       this.fechaBaja = fechaBaja;
       this.motivoBaja = motivoBaja;
       this.pedidoproductosterminadoses = pedidoproductosterminadoses;
       this.notificacionreaprovisionamientos = notificacionreaprovisionamientos;
       this.pagos = pagos;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public String getMotivoBaja() {
        return this.motivoBaja;
    }
    
    public void setMotivoBaja(String motivoBaja) {
        this.motivoBaja = motivoBaja;
    }
    public Set getPedidoproductosterminadoses() {
        return this.pedidoproductosterminadoses;
    }
    
    public void setPedidoproductosterminadoses(Set pedidoproductosterminadoses) {
        this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }
    public Set getNotificacionreaprovisionamientos() {
        return this.notificacionreaprovisionamientos;
    }
    
    public void setNotificacionreaprovisionamientos(Set notificacionreaprovisionamientos) {
        this.notificacionreaprovisionamientos = notificacionreaprovisionamientos;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


