package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadocobropedido generated by hbm2java
 */
public class Estadocobropedido  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set cobropedidos = new HashSet(0);

    public Estadocobropedido() {
    }

	
    public Estadocobropedido(String nombre) {
        this.nombre = nombre;
    }
    public Estadocobropedido(String nombre, Set cobropedidos) {
       this.nombre = nombre;
       this.cobropedidos = cobropedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCobropedidos() {
        return this.cobropedidos;
    }
    
    public void setCobropedidos(Set cobropedidos) {
        this.cobropedidos = cobropedidos;
    }




}


