package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadodetalleventa generated by hbm2java
 */
public class Estadodetalleventa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set detalleventas = new HashSet(0);

    public Estadodetalleventa() {
    }

	
    public Estadodetalleventa(String nombre) {
        this.nombre = nombre;
    }
    public Estadodetalleventa(String nombre, Set detalleventas) {
       this.nombre = nombre;
       this.detalleventas = detalleventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


