package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadocartera generated by hbm2java
 */
public class Estadocartera  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set detallecarteras = new HashSet(0);

    public Estadocartera() {
    }

	
    public Estadocartera(String nombre) {
        this.nombre = nombre;
    }
    public Estadocartera(String nombre, Set detallecarteras) {
       this.nombre = nombre;
       this.detallecarteras = detallecarteras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDetallecarteras() {
        return this.detallecarteras;
    }
    
    public void setDetallecarteras(Set detallecarteras) {
        this.detallecarteras = detallecarteras;
    }




}


