package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadoordencompra generated by hbm2java
 */
@Entity
@Table(name="estadoordencompra"
    ,catalog="seee"
)
public class Estadoordencompra  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Ordencompra> ordencompras = new HashSet<Ordencompra>(0);

    public Estadoordencompra() {
    }

	
    public Estadoordencompra(String nombre) {
        this.nombre = nombre;
    }
    public Estadoordencompra(String nombre, Set<Ordencompra> ordencompras) {
       this.nombre = nombre;
       this.ordencompras = ordencompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadoordencompra")
    public Set<Ordencompra> getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set<Ordencompra> ordencompras) {
        this.ordencompras = ordencompras;
    }




}


