package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadocobrocheque generated by hbm2java
 */
public class Estadocobrocheque  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set cobrocheques = new HashSet(0);

    public Estadocobrocheque() {
    }

	
    public Estadocobrocheque(String nombre) {
        this.nombre = nombre;
    }
    public Estadocobrocheque(String nombre, Set cobrocheques) {
       this.nombre = nombre;
       this.cobrocheques = cobrocheques;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCobrocheques() {
        return this.cobrocheques;
    }
    
    public void setCobrocheques(Set cobrocheques) {
        this.cobrocheques = cobrocheques;
    }




}


