package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer id;
     private Pedidoproductosterminados pedidoproductosterminados;
     private Tipofactura tipofactura;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Tipofactura tipofactura) {
        this.tipofactura = tipofactura;
    }
    public Factura(Pedidoproductosterminados pedidoproductosterminados, Tipofactura tipofactura, Set detallefacturas) {
       this.pedidoproductosterminados = pedidoproductosterminados;
       this.tipofactura = tipofactura;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedidoproductosterminados getPedidoproductosterminados() {
        return this.pedidoproductosterminados;
    }
    
    public void setPedidoproductosterminados(Pedidoproductosterminados pedidoproductosterminados) {
        this.pedidoproductosterminados = pedidoproductosterminados;
    }
    public Tipofactura getTipofactura() {
        return this.tipofactura;
    }
    
    public void setTipofactura(Tipofactura tipofactura) {
        this.tipofactura = tipofactura;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


