package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Importacion generated by hbm2java
 */
public class Importacion  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Date fecha;
     private String lugarOrigen;
     private Float pagoAduana;
     private Date fechaEmbarque;
     private Set ordencompraximportacions = new HashSet(0);

    public Importacion() {
    }

	
    public Importacion(Compra compra, Date fecha, String lugarOrigen) {
        this.compra = compra;
        this.fecha = fecha;
        this.lugarOrigen = lugarOrigen;
    }
    public Importacion(Compra compra, Date fecha, String lugarOrigen, Float pagoAduana, Date fechaEmbarque, Set ordencompraximportacions) {
       this.compra = compra;
       this.fecha = fecha;
       this.lugarOrigen = lugarOrigen;
       this.pagoAduana = pagoAduana;
       this.fechaEmbarque = fechaEmbarque;
       this.ordencompraximportacions = ordencompraximportacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getLugarOrigen() {
        return this.lugarOrigen;
    }
    
    public void setLugarOrigen(String lugarOrigen) {
        this.lugarOrigen = lugarOrigen;
    }
    public Float getPagoAduana() {
        return this.pagoAduana;
    }
    
    public void setPagoAduana(Float pagoAduana) {
        this.pagoAduana = pagoAduana;
    }
    public Date getFechaEmbarque() {
        return this.fechaEmbarque;
    }
    
    public void setFechaEmbarque(Date fechaEmbarque) {
        this.fechaEmbarque = fechaEmbarque;
    }
    public Set getOrdencompraximportacions() {
        return this.ordencompraximportacions;
    }
    
    public void setOrdencompraximportacions(Set ordencompraximportacions) {
        this.ordencompraximportacions = ordencompraximportacions;
    }




}


