package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private Integer id;
     private Provincia provincia;
     private String nombre;
     private Set barrios = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(Provincia provincia) {
        this.provincia = provincia;
    }
    public Localidad(Provincia provincia, String nombre, Set barrios) {
       this.provincia = provincia;
       this.nombre = nombre;
       this.barrios = barrios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getBarrios() {
        return this.barrios;
    }
    
    public void setBarrios(Set barrios) {
        this.barrios = barrios;
    }




}


