package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lote generated by hbm2java
 */
@Entity
@Table(name="lote"
    ,catalog="seee"
)
public class Lote  implements java.io.Serializable {


     private Integer id;
     private Productoterminado productoterminado;
     private int nroLote;
     private int cantidadProducida;
     private Set<Detallemateriaprima> detallemateriaprimas = new HashSet<Detallemateriaprima>(0);

    public Lote() {
    }

	
    public Lote(Productoterminado productoterminado, int nroLote, int cantidadProducida) {
        this.productoterminado = productoterminado;
        this.nroLote = nroLote;
        this.cantidadProducida = cantidadProducida;
    }
    public Lote(Productoterminado productoterminado, int nroLote, int cantidadProducida, Set<Detallemateriaprima> detallemateriaprimas) {
       this.productoterminado = productoterminado;
       this.nroLote = nroLote;
       this.cantidadProducida = cantidadProducida;
       this.detallemateriaprimas = detallemateriaprimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
    
    @Column(name="nroLote", nullable=false)
    public int getNroLote() {
        return this.nroLote;
    }
    
    public void setNroLote(int nroLote) {
        this.nroLote = nroLote;
    }
    
    @Column(name="cantidadProducida", nullable=false)
    public int getCantidadProducida() {
        return this.cantidadProducida;
    }
    
    public void setCantidadProducida(int cantidadProducida) {
        this.cantidadProducida = cantidadProducida;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lote")
    public Set<Detallemateriaprima> getDetallemateriaprimas() {
        return this.detallemateriaprimas;
    }
    
    public void setDetallemateriaprimas(Set<Detallemateriaprima> detallemateriaprimas) {
        this.detallemateriaprimas = detallemateriaprimas;
    }




}


