package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Muestrario generated by hbm2java
 */
public class Muestrario  implements java.io.Serializable {


     private Integer id;
     private Date fechaDesde;
     private Date fechaHasta;
     private Set productoterminados = new HashSet(0);

    public Muestrario() {
    }

	
    public Muestrario(Date fechaDesde, Date fechaHasta) {
        this.fechaDesde = fechaDesde;
        this.fechaHasta = fechaHasta;
    }
    public Muestrario(Date fechaDesde, Date fechaHasta, Set productoterminados) {
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.productoterminados = productoterminados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
    public Set getProductoterminados() {
        return this.productoterminados;
    }
    
    public void setProductoterminados(Set productoterminados) {
        this.productoterminados = productoterminados;
    }




}


