package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Muestrario generated by hbm2java
 */
@Entity
@Table(name="muestrario"
    ,catalog="seee"
)
public class Muestrario  implements java.io.Serializable {


     private Integer id;
     private Date fechaDesde;
     private Date fechaHasta;
     private Set<Productoterminado> productoterminados = new HashSet<Productoterminado>(0);

    public Muestrario() {
    }

	
    public Muestrario(Date fechaDesde, Date fechaHasta) {
        this.fechaDesde = fechaDesde;
        this.fechaHasta = fechaHasta;
    }
    public Muestrario(Date fechaDesde, Date fechaHasta, Set<Productoterminado> productoterminados) {
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.productoterminados = productoterminados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaDesde", nullable=false, length=10)
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaHasta", nullable=false, length=10)
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="muestrario")
    public Set<Productoterminado> getProductoterminados() {
        return this.productoterminados;
    }
    
    public void setProductoterminados(Set<Productoterminado> productoterminados) {
        this.productoterminados = productoterminados;
    }




}


