package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordencompraximportacion generated by hbm2java
 */
@Entity
@Table(name="ordencompraximportacion"
    ,catalog="seee"
)
public class Ordencompraximportacion  implements java.io.Serializable {


     private Integer id;
     private Importacion importacion;
     private Ordencompra ordencompra;

    public Ordencompraximportacion() {
    }

    public Ordencompraximportacion(Importacion importacion, Ordencompra ordencompra) {
       this.importacion = importacion;
       this.ordencompra = ordencompra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idImportacion", nullable=false)
    public Importacion getImportacion() {
        return this.importacion;
    }
    
    public void setImportacion(Importacion importacion) {
        this.importacion = importacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idOrdenCompra", nullable=false)
    public Ordencompra getOrdencompra() {
        return this.ordencompra;
    }
    
    public void setOrdencompra(Ordencompra ordencompra) {
        this.ordencompra = ordencompra;
    }




}


