package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordencompra generated by hbm2java
 */
public class Ordencompra  implements java.io.Serializable {


     private Integer id;
     private Proveedor proveedor;
     private Estadoordencompra estadoordencompra;
     private Empresatransporte empresatransporteByIdEmpresaTransporteExterior;
     private Empresatransporte empresatransporteByIdEmpresaTransporteInterior;
     private Date fechaPedido;
     private Date fechaEstimadaLlegada;
     private Float otrosGastos;
     private Set ordencompraximportacions = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Ordencompra() {
    }

	
    public Ordencompra(Estadoordencompra estadoordencompra, Date fechaPedido) {
        this.estadoordencompra = estadoordencompra;
        this.fechaPedido = fechaPedido;
    }
    public Ordencompra(Proveedor proveedor, Estadoordencompra estadoordencompra, Empresatransporte empresatransporteByIdEmpresaTransporteExterior, Empresatransporte empresatransporteByIdEmpresaTransporteInterior, Date fechaPedido, Date fechaEstimadaLlegada, Float otrosGastos, Set ordencompraximportacions, Set pagos) {
       this.proveedor = proveedor;
       this.estadoordencompra = estadoordencompra;
       this.empresatransporteByIdEmpresaTransporteExterior = empresatransporteByIdEmpresaTransporteExterior;
       this.empresatransporteByIdEmpresaTransporteInterior = empresatransporteByIdEmpresaTransporteInterior;
       this.fechaPedido = fechaPedido;
       this.fechaEstimadaLlegada = fechaEstimadaLlegada;
       this.otrosGastos = otrosGastos;
       this.ordencompraximportacions = ordencompraximportacions;
       this.pagos = pagos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Estadoordencompra getEstadoordencompra() {
        return this.estadoordencompra;
    }
    
    public void setEstadoordencompra(Estadoordencompra estadoordencompra) {
        this.estadoordencompra = estadoordencompra;
    }
    public Empresatransporte getEmpresatransporteByIdEmpresaTransporteExterior() {
        return this.empresatransporteByIdEmpresaTransporteExterior;
    }
    
    public void setEmpresatransporteByIdEmpresaTransporteExterior(Empresatransporte empresatransporteByIdEmpresaTransporteExterior) {
        this.empresatransporteByIdEmpresaTransporteExterior = empresatransporteByIdEmpresaTransporteExterior;
    }
    public Empresatransporte getEmpresatransporteByIdEmpresaTransporteInterior() {
        return this.empresatransporteByIdEmpresaTransporteInterior;
    }
    
    public void setEmpresatransporteByIdEmpresaTransporteInterior(Empresatransporte empresatransporteByIdEmpresaTransporteInterior) {
        this.empresatransporteByIdEmpresaTransporteInterior = empresatransporteByIdEmpresaTransporteInterior;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaEstimadaLlegada() {
        return this.fechaEstimadaLlegada;
    }
    
    public void setFechaEstimadaLlegada(Date fechaEstimadaLlegada) {
        this.fechaEstimadaLlegada = fechaEstimadaLlegada;
    }
    public Float getOtrosGastos() {
        return this.otrosGastos;
    }
    
    public void setOtrosGastos(Float otrosGastos) {
        this.otrosGastos = otrosGastos;
    }
    public Set getOrdencompraximportacions() {
        return this.ordencompraximportacions;
    }
    
    public void setOrdencompraximportacions(Set ordencompraximportacions) {
        this.ordencompraximportacions = ordencompraximportacions;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


