package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private Tipodni tipodni;
     private String nombre;
     private String apellido;
     private String telefono;
     private String celular;
     private String dni;
     private String mail;
     private Set viajantes = new HashSet(0);
     private Set empresaclientexpersonas = new HashSet(0);
     private Set empleados = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Persona(Domicilio domicilio, Tipodni tipodni, String nombre, String apellido, String telefono, String celular, String dni, String mail, Set viajantes, Set empresaclientexpersonas, Set empleados) {
       this.domicilio = domicilio;
       this.tipodni = tipodni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.celular = celular;
       this.dni = dni;
       this.mail = mail;
       this.viajantes = viajantes;
       this.empresaclientexpersonas = empresaclientexpersonas;
       this.empleados = empleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    public Tipodni getTipodni() {
        return this.tipodni;
    }
    
    public void setTipodni(Tipodni tipodni) {
        this.tipodni = tipodni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Set getViajantes() {
        return this.viajantes;
    }
    
    public void setViajantes(Set viajantes) {
        this.viajantes = viajantes;
    }
    public Set getEmpresaclientexpersonas() {
        return this.empresaclientexpersonas;
    }
    
    public void setEmpresaclientexpersonas(Set empresaclientexpersonas) {
        this.empresaclientexpersonas = empresaclientexpersonas;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


