package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productoterminado generated by hbm2java
 */
public class Productoterminado  implements java.io.Serializable {


     private Integer id;
     private Modelo modelo;
     private Color color;
     private Muestrario muestrario;
     private Marca marca;
     private Tamano tamano;
     private Ubicacion ubicacion;
     private int nroProducto;
     private Float precioEstimado;
     private String nombre;
     private int nivelReaprovisionamiento;
     private int stockMaximo;
     private Date fechaIngreso;
     private int stockActual;
     private Float precioVenta;
     private Set productoimportados = new HashSet(0);
     private Set detallepedidoproductosterminadoses = new HashSet(0);
     private Set lotes = new HashSet(0);
     private Set accesorios = new HashSet(0);
     private Set productofabricados = new HashSet(0);
     private Set detalleventas = new HashSet(0);

    public Productoterminado() {
    }

	
    public Productoterminado(Modelo modelo, Color color, Marca marca, Tamano tamano, Ubicacion ubicacion, int nroProducto, String nombre, int nivelReaprovisionamiento, int stockMaximo, Date fechaIngreso, int stockActual) {
        this.modelo = modelo;
        this.color = color;
        this.marca = marca;
        this.tamano = tamano;
        this.ubicacion = ubicacion;
        this.nroProducto = nroProducto;
        this.nombre = nombre;
        this.nivelReaprovisionamiento = nivelReaprovisionamiento;
        this.stockMaximo = stockMaximo;
        this.fechaIngreso = fechaIngreso;
        this.stockActual = stockActual;
    }
    public Productoterminado(Modelo modelo, Color color, Muestrario muestrario, Marca marca, Tamano tamano, Ubicacion ubicacion, int nroProducto, Float precioEstimado, String nombre, int nivelReaprovisionamiento, int stockMaximo, Date fechaIngreso, int stockActual, Float precioVenta, Set productoimportados, Set detallepedidoproductosterminadoses, Set lotes, Set accesorios, Set productofabricados, Set detalleventas) {
       this.modelo = modelo;
       this.color = color;
       this.muestrario = muestrario;
       this.marca = marca;
       this.tamano = tamano;
       this.ubicacion = ubicacion;
       this.nroProducto = nroProducto;
       this.precioEstimado = precioEstimado;
       this.nombre = nombre;
       this.nivelReaprovisionamiento = nivelReaprovisionamiento;
       this.stockMaximo = stockMaximo;
       this.fechaIngreso = fechaIngreso;
       this.stockActual = stockActual;
       this.precioVenta = precioVenta;
       this.productoimportados = productoimportados;
       this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
       this.lotes = lotes;
       this.accesorios = accesorios;
       this.productofabricados = productofabricados;
       this.detalleventas = detalleventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Muestrario getMuestrario() {
        return this.muestrario;
    }
    
    public void setMuestrario(Muestrario muestrario) {
        this.muestrario = muestrario;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Tamano getTamano() {
        return this.tamano;
    }
    
    public void setTamano(Tamano tamano) {
        this.tamano = tamano;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public int getNroProducto() {
        return this.nroProducto;
    }
    
    public void setNroProducto(int nroProducto) {
        this.nroProducto = nroProducto;
    }
    public Float getPrecioEstimado() {
        return this.precioEstimado;
    }
    
    public void setPrecioEstimado(Float precioEstimado) {
        this.precioEstimado = precioEstimado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNivelReaprovisionamiento() {
        return this.nivelReaprovisionamiento;
    }
    
    public void setNivelReaprovisionamiento(int nivelReaprovisionamiento) {
        this.nivelReaprovisionamiento = nivelReaprovisionamiento;
    }
    public int getStockMaximo() {
        return this.stockMaximo;
    }
    
    public void setStockMaximo(int stockMaximo) {
        this.stockMaximo = stockMaximo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public int getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }
    public Float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Float precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Set getProductoimportados() {
        return this.productoimportados;
    }
    
    public void setProductoimportados(Set productoimportados) {
        this.productoimportados = productoimportados;
    }
    public Set getDetallepedidoproductosterminadoses() {
        return this.detallepedidoproductosterminadoses;
    }
    
    public void setDetallepedidoproductosterminadoses(Set detallepedidoproductosterminadoses) {
        this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }
    public Set getAccesorios() {
        return this.accesorios;
    }
    
    public void setAccesorios(Set accesorios) {
        this.accesorios = accesorios;
    }
    public Set getProductofabricados() {
        return this.productofabricados;
    }
    
    public void setProductofabricados(Set productofabricados) {
        this.productofabricados = productofabricados;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


