package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productosdefectuosos generated by hbm2java
 */
@Entity
@Table(name="productosdefectuosos"
    ,catalog="seee"
)
public class Productosdefectuosos  implements java.io.Serializable {


     private Integer id;
     private Tipodefecto tipodefecto;
     private int cantidad;
     private Set<Productosdefectuososxcompra> productosdefectuososxcompras = new HashSet<Productosdefectuososxcompra>(0);

    public Productosdefectuosos() {
    }

	
    public Productosdefectuosos(Tipodefecto tipodefecto, int cantidad) {
        this.tipodefecto = tipodefecto;
        this.cantidad = cantidad;
    }
    public Productosdefectuosos(Tipodefecto tipodefecto, int cantidad, Set<Productosdefectuososxcompra> productosdefectuososxcompras) {
       this.tipodefecto = tipodefecto;
       this.cantidad = cantidad;
       this.productosdefectuososxcompras = productosdefectuososxcompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoDefecto", nullable=false)
    public Tipodefecto getTipodefecto() {
        return this.tipodefecto;
    }
    
    public void setTipodefecto(Tipodefecto tipodefecto) {
        this.tipodefecto = tipodefecto;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="productosdefectuosos")
    public Set<Productosdefectuososxcompra> getProductosdefectuososxcompras() {
        return this.productosdefectuososxcompras;
    }
    
    public void setProductosdefectuososxcompras(Set<Productosdefectuososxcompra> productosdefectuososxcompras) {
        this.productosdefectuososxcompras = productosdefectuososxcompras;
    }




}


