package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Productosdefectuososxcompra generated by hbm2java
 */
public class Productosdefectuososxcompra  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Productosdefectuosos productosdefectuosos;

    public Productosdefectuososxcompra() {
    }

    public Productosdefectuososxcompra(Compra compra, Productosdefectuosos productosdefectuosos) {
       this.compra = compra;
       this.productosdefectuosos = productosdefectuosos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Productosdefectuosos getProductosdefectuosos() {
        return this.productosdefectuosos;
    }
    
    public void setProductosdefectuosos(Productosdefectuosos productosdefectuosos) {
        this.productosdefectuosos = productosdefectuosos;
    }




}


