package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Productosdefectuosos generated by hbm2java
 */
public class Productosdefectuosos  implements java.io.Serializable {


     private Integer id;
     private Tipodefecto tipodefecto;
     private int cantidad;
     private Set productosdefectuososxcompras = new HashSet(0);

    public Productosdefectuosos() {
    }

	
    public Productosdefectuosos(Tipodefecto tipodefecto, int cantidad) {
        this.tipodefecto = tipodefecto;
        this.cantidad = cantidad;
    }
    public Productosdefectuosos(Tipodefecto tipodefecto, int cantidad, Set productosdefectuososxcompras) {
       this.tipodefecto = tipodefecto;
       this.cantidad = cantidad;
       this.productosdefectuososxcompras = productosdefectuososxcompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipodefecto getTipodefecto() {
        return this.tipodefecto;
    }
    
    public void setTipodefecto(Tipodefecto tipodefecto) {
        this.tipodefecto = tipodefecto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getProductosdefectuososxcompras() {
        return this.productosdefectuososxcompras;
    }
    
    public void setProductosdefectuososxcompras(Set productosdefectuososxcompras) {
        this.productosdefectuososxcompras = productosdefectuososxcompras;
    }




}


