package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="seee"
)
public class Proveedor  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private String nombre;
     private String razonSocial;
     private String mail;
     private String telefonoFijo;
     private String telefonoCelular;
     private String pais;
     private Date fechaAlta;
     private Set<Ordencompra> ordencompras = new HashSet<Ordencompra>(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, Date fechaAlta) {
        this.nombre = nombre;
        this.fechaAlta = fechaAlta;
    }
    public Proveedor(Domicilio domicilio, String nombre, String razonSocial, String mail, String telefonoFijo, String telefonoCelular, String pais, Date fechaAlta, Set<Ordencompra> ordencompras) {
       this.domicilio = domicilio;
       this.nombre = nombre;
       this.razonSocial = razonSocial;
       this.mail = mail;
       this.telefonoFijo = telefonoFijo;
       this.telefonoCelular = telefonoCelular;
       this.pais = pais;
       this.fechaAlta = fechaAlta;
       this.ordencompras = ordencompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDomicilioa")
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="razonSocial", length=20)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="mail", length=30)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name="telefonoFijo", length=20)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    
    @Column(name="telefonoCelular", length=20)
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    
    @Column(name="pais", length=20)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaAlta", nullable=false, length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Ordencompra> getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set<Ordencompra> ordencompras) {
        this.ordencompras = ordencompras;
    }




}


