package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,catalog="seee"
)
public class Venta  implements java.io.Serializable {


     private Integer id;
     private Cobropedido cobropedido;
     private Pedidoproductosterminados pedidoproductosterminados;
     private Estadoventa estadoventa;
     private Date fechaVenta;
     private int nroFactura;
     private Date fechaMaximaDevolucion;
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);

    public Venta() {
    }

	
    public Venta(Cobropedido cobropedido, Pedidoproductosterminados pedidoproductosterminados, Estadoventa estadoventa, Date fechaVenta, int nroFactura) {
        this.cobropedido = cobropedido;
        this.pedidoproductosterminados = pedidoproductosterminados;
        this.estadoventa = estadoventa;
        this.fechaVenta = fechaVenta;
        this.nroFactura = nroFactura;
    }
    public Venta(Cobropedido cobropedido, Pedidoproductosterminados pedidoproductosterminados, Estadoventa estadoventa, Date fechaVenta, int nroFactura, Date fechaMaximaDevolucion, Set<Detalleventa> detalleventas) {
       this.cobropedido = cobropedido;
       this.pedidoproductosterminados = pedidoproductosterminados;
       this.estadoventa = estadoventa;
       this.fechaVenta = fechaVenta;
       this.nroFactura = nroFactura;
       this.fechaMaximaDevolucion = fechaMaximaDevolucion;
       this.detalleventas = detalleventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCobroPedido", nullable=false)
    public Cobropedido getCobropedido() {
        return this.cobropedido;
    }
    
    public void setCobropedido(Cobropedido cobropedido) {
        this.cobropedido = cobropedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPedidoProductosTerminados", nullable=false)
    public Pedidoproductosterminados getPedidoproductosterminados() {
        return this.pedidoproductosterminados;
    }
    
    public void setPedidoproductosterminados(Pedidoproductosterminados pedidoproductosterminados) {
        this.pedidoproductosterminados = pedidoproductosterminados;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoVenta", nullable=false)
    public Estadoventa getEstadoventa() {
        return this.estadoventa;
    }
    
    public void setEstadoventa(Estadoventa estadoventa) {
        this.estadoventa = estadoventa;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaVenta", nullable=false, length=10)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    
    @Column(name="nroFactura", nullable=false)
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaMaximaDevolucion", length=10)
    public Date getFechaMaximaDevolucion() {
        return this.fechaMaximaDevolucion;
    }
    
    public void setFechaMaximaDevolucion(Date fechaMaximaDevolucion) {
        this.fechaMaximaDevolucion = fechaMaximaDevolucion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="venta")
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }




}


