package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer id;
     private Cobropedido cobropedido;
     private Pedidoproductosterminados pedidoproductosterminados;
     private Estadoventa estadoventa;
     private Date fechaVenta;
     private int nroFactura;
     private Date fechaMaximaDevolucion;
     private Set detalleventas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(Cobropedido cobropedido, Pedidoproductosterminados pedidoproductosterminados, Estadoventa estadoventa, Date fechaVenta, int nroFactura) {
        this.cobropedido = cobropedido;
        this.pedidoproductosterminados = pedidoproductosterminados;
        this.estadoventa = estadoventa;
        this.fechaVenta = fechaVenta;
        this.nroFactura = nroFactura;
    }
    public Venta(Cobropedido cobropedido, Pedidoproductosterminados pedidoproductosterminados, Estadoventa estadoventa, Date fechaVenta, int nroFactura, Date fechaMaximaDevolucion, Set detalleventas) {
       this.cobropedido = cobropedido;
       this.pedidoproductosterminados = pedidoproductosterminados;
       this.estadoventa = estadoventa;
       this.fechaVenta = fechaVenta;
       this.nroFactura = nroFactura;
       this.fechaMaximaDevolucion = fechaMaximaDevolucion;
       this.detalleventas = detalleventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cobropedido getCobropedido() {
        return this.cobropedido;
    }
    
    public void setCobropedido(Cobropedido cobropedido) {
        this.cobropedido = cobropedido;
    }
    public Pedidoproductosterminados getPedidoproductosterminados() {
        return this.pedidoproductosterminados;
    }
    
    public void setPedidoproductosterminados(Pedidoproductosterminados pedidoproductosterminados) {
        this.pedidoproductosterminados = pedidoproductosterminados;
    }
    public Estadoventa getEstadoventa() {
        return this.estadoventa;
    }
    
    public void setEstadoventa(Estadoventa estadoventa) {
        this.estadoventa = estadoventa;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public int getNroFactura() {
        return this.nroFactura;
    }
    
    public void setNroFactura(int nroFactura) {
        this.nroFactura = nroFactura;
    }
    public Date getFechaMaximaDevolucion() {
        return this.fechaMaximaDevolucion;
    }
    
    public void setFechaMaximaDevolucion(Date fechaMaximaDevolucion) {
        this.fechaMaximaDevolucion = fechaMaximaDevolucion;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


