package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Viajante generated by hbm2java
 */
public class Viajante  implements java.io.Serializable {


     private int idPersona;
     private Persona persona;
     private Detallecartera detallecartera;
     private int comisionPorVenta;
     private Set pedidoproductosterminadoses = new HashSet(0);
     private Set devolucionproductosterminadoses = new HashSet(0);
     private Set barrios = new HashSet(0);

    public Viajante() {
    }

	
    public Viajante(int idPersona, Persona persona, Detallecartera detallecartera, int comisionPorVenta) {
        this.idPersona = idPersona;
        this.persona = persona;
        this.detallecartera = detallecartera;
        this.comisionPorVenta = comisionPorVenta;
    }
    public Viajante(int idPersona, Persona persona, Detallecartera detallecartera, int comisionPorVenta, Set pedidoproductosterminadoses, Set devolucionproductosterminadoses, Set barrios) {
       this.idPersona = idPersona;
       this.persona = persona;
       this.detallecartera = detallecartera;
       this.comisionPorVenta = comisionPorVenta;
       this.pedidoproductosterminadoses = pedidoproductosterminadoses;
       this.devolucionproductosterminadoses = devolucionproductosterminadoses;
       this.barrios = barrios;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Detallecartera getDetallecartera() {
        return this.detallecartera;
    }
    
    public void setDetallecartera(Detallecartera detallecartera) {
        this.detallecartera = detallecartera;
    }
    public int getComisionPorVenta() {
        return this.comisionPorVenta;
    }
    
    public void setComisionPorVenta(int comisionPorVenta) {
        this.comisionPorVenta = comisionPorVenta;
    }
    public Set getPedidoproductosterminadoses() {
        return this.pedidoproductosterminadoses;
    }
    
    public void setPedidoproductosterminadoses(Set pedidoproductosterminadoses) {
        this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }
    public Set getDevolucionproductosterminadoses() {
        return this.devolucionproductosterminadoses;
    }
    
    public void setDevolucionproductosterminadoses(Set devolucionproductosterminadoses) {
        this.devolucionproductosterminadoses = devolucionproductosterminadoses;
    }
    public Set getBarrios() {
        return this.barrios;
    }
    
    public void setBarrios(Set barrios) {
        this.barrios = barrios;
    }




}


