package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accesorio generated by hbm2java
 */
@Entity
@Table(name="accesorio"
    ,catalog="seee"
)
public class Accesorio  implements java.io.Serializable {


     private Integer id;
     private Productoterminado productoterminado;
     private Tipoaccesorio tipoaccesorio;
     private String nombre;

    public Accesorio() {
    }

    public Accesorio(Productoterminado productoterminado, Tipoaccesorio tipoaccesorio, String nombre) {
       this.productoterminado = productoterminado;
       this.tipoaccesorio = tipoaccesorio;
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProducto", nullable=false)
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoaccesorio", nullable=false)
    public Tipoaccesorio getTipoaccesorio() {
        return this.tipoaccesorio;
    }
    
    public void setTipoaccesorio(Tipoaccesorio tipoaccesorio) {
        this.tipoaccesorio = tipoaccesorio;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


