package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Barrio generated by hbm2java
 */
@Entity
@Table(name="barrio"
    ,catalog="seee"
)
public class Barrio  implements java.io.Serializable {


     private Integer id;
     private Localidad localidad;
     private Viajante viajante;
     private String nombre;
     private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);

    public Barrio() {
    }

	
    public Barrio(Localidad localidad, String nombre) {
        this.localidad = localidad;
        this.nombre = nombre;
    }
    public Barrio(Localidad localidad, Viajante viajante, String nombre, Set<Domicilio> domicilios) {
       this.localidad = localidad;
       this.viajante = viajante;
       this.nombre = nombre;
       this.domicilios = domicilios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLocalidad", nullable=false)
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idViajante")
    public Viajante getViajante() {
        return this.viajante;
    }
    
    public void setViajante(Viajante viajante) {
        this.viajante = viajante;
    }
    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="barrio")
    public Set<Domicilio> getDomicilios() {
        return this.domicilios;
    }
    
    public void setDomicilios(Set<Domicilio> domicilios) {
        this.domicilios = domicilios;
    }




}


