package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="cargo"
    ,catalog="seee"
)
public class Cargo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private float precioPorHora;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Cargo() {
    }

	
    public Cargo(String nombre, float precioPorHora) {
        this.nombre = nombre;
        this.precioPorHora = precioPorHora;
    }
    public Cargo(String nombre, String descripcion, float precioPorHora, Set<Empleado> empleados) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioPorHora = precioPorHora;
       this.empleados = empleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precioPorHora", nullable=false, precision=9)
    public float getPrecioPorHora() {
        return this.precioPorHora;
    }
    
    public void setPrecioPorHora(float precioPorHora) {
        this.precioPorHora = precioPorHora;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cargo")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


