package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private float precioPorHora;
     private Set empleados = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String nombre, float precioPorHora) {
        this.nombre = nombre;
        this.precioPorHora = precioPorHora;
    }
    public Cargo(String nombre, String descripcion, float precioPorHora, Set empleados) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioPorHora = precioPorHora;
       this.empleados = empleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public float getPrecioPorHora() {
        return this.precioPorHora;
    }
    
    public void setPrecioPorHora(float precioPorHora) {
        this.precioPorHora = precioPorHora;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


