package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Cobroefectivo generated by hbm2java
 */
public class Cobroefectivo  implements java.io.Serializable {


     private int idDetalleCobroPedido;
     private Detallecobropedido detallecobropedido;

    public Cobroefectivo() {
    }

    public Cobroefectivo(int idDetalleCobroPedido, Detallecobropedido detallecobropedido) {
       this.idDetalleCobroPedido = idDetalleCobroPedido;
       this.detallecobropedido = detallecobropedido;
    }
   
    public int getIdDetalleCobroPedido() {
        return this.idDetalleCobroPedido;
    }
    
    public void setIdDetalleCobroPedido(int idDetalleCobroPedido) {
        this.idDetalleCobroPedido = idDetalleCobroPedido;
    }
    public Detallecobropedido getDetallecobropedido() {
        return this.detallecobropedido;
    }
    
    public void setDetallecobropedido(Detallecobropedido detallecobropedido) {
        this.detallecobropedido = detallecobropedido;
    }




}


