package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cobrocheque generated by hbm2java
 */
@Entity
@Table(name="cobrocheque"
    ,catalog="seee"
)
public class Cobrocheque  implements java.io.Serializable {


     private int idDetalleCobroPedido;
     private Estadocobrocheque estadocobrocheque;
     private Detallecobropedido detallecobropedido;
     private Cheque cheque;

    public Cobrocheque() {
    }

    public Cobrocheque(int idDetalleCobroPedido, Estadocobrocheque estadocobrocheque, Detallecobropedido detallecobropedido, Cheque cheque) {
       this.idDetalleCobroPedido = idDetalleCobroPedido;
       this.estadocobrocheque = estadocobrocheque;
       this.detallecobropedido = detallecobropedido;
       this.cheque = cheque;
    }
   
     @Id 
    
    @Column(name="idDetalleCobroPedido", unique=true, nullable=false)
    public int getIdDetalleCobroPedido() {
        return this.idDetalleCobroPedido;
    }
    
    public void setIdDetalleCobroPedido(int idDetalleCobroPedido) {
        this.idDetalleCobroPedido = idDetalleCobroPedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoCobroCheque", nullable=false)
    public Estadocobrocheque getEstadocobrocheque() {
        return this.estadocobrocheque;
    }
    
    public void setEstadocobrocheque(Estadocobrocheque estadocobrocheque) {
        this.estadocobrocheque = estadocobrocheque;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDetalleCobroPedido", unique=true, nullable=false, insertable=false, updatable=false)
    public Detallecobropedido getDetallecobropedido() {
        return this.detallecobropedido;
    }
    
    public void setDetallecobropedido(Detallecobropedido detallecobropedido) {
        this.detallecobropedido = detallecobropedido;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCheque", nullable=false)
    public Cheque getCheque() {
        return this.cheque;
    }
    
    public void setCheque(Cheque cheque) {
        this.cheque = cheque;
    }




}


