package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Date fechaRealLlegada;
     private Set productosdefectuososxcompras = new HashSet(0);
     private Set importacions = new HashSet(0);
     private Set detallecompras = new HashSet(0);

    public Compra() {
    }

    public Compra(Date fechaRealLlegada, Set productosdefectuososxcompras, Set importacions, Set detallecompras) {
       this.fechaRealLlegada = fechaRealLlegada;
       this.productosdefectuososxcompras = productosdefectuososxcompras;
       this.importacions = importacions;
       this.detallecompras = detallecompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechaRealLlegada() {
        return this.fechaRealLlegada;
    }
    
    public void setFechaRealLlegada(Date fechaRealLlegada) {
        this.fechaRealLlegada = fechaRealLlegada;
    }
    public Set getProductosdefectuososxcompras() {
        return this.productosdefectuososxcompras;
    }
    
    public void setProductosdefectuososxcompras(Set productosdefectuososxcompras) {
        this.productosdefectuososxcompras = productosdefectuososxcompras;
    }
    public Set getImportacions() {
        return this.importacions;
    }
    
    public void setImportacions(Set importacions) {
        this.importacions = importacions;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


