package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Condicioniva generated by hbm2java
 */
public class Condicioniva  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set empresaclientes = new HashSet(0);

    public Condicioniva() {
    }

	
    public Condicioniva(String nombre) {
        this.nombre = nombre;
    }
    public Condicioniva(String nombre, String descripcion, Set empresaclientes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.empresaclientes = empresaclientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set empresaclientes) {
        this.empresaclientes = empresaclientes;
    }




}


