package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Creditocliente generated by hbm2java
 */
public class Creditocliente  implements java.io.Serializable {


     private Integer id;
     private float monto;
     private Set empresaclientes = new HashSet(0);
     private Set detallecobropedidos = new HashSet(0);

    public Creditocliente() {
    }

	
    public Creditocliente(float monto) {
        this.monto = monto;
    }
    public Creditocliente(float monto, Set empresaclientes, Set detallecobropedidos) {
       this.monto = monto;
       this.empresaclientes = empresaclientes;
       this.detallecobropedidos = detallecobropedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    public Set getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set empresaclientes) {
        this.empresaclientes = empresaclientes;
    }
    public Set getDetallecobropedidos() {
        return this.detallecobropedidos;
    }
    
    public void setDetallecobropedidos(Set detallecobropedidos) {
        this.detallecobropedidos = detallecobropedidos;
    }




}


