package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Detalledevolucionproductosterminados generated by hbm2java
 */
public class Detalledevolucionproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Detalleventa detalleventa;
     private Devolucionproductosterminados devolucionproductosterminados;

    public Detalledevolucionproductosterminados() {
    }

    public Detalledevolucionproductosterminados(Detalleventa detalleventa, Devolucionproductosterminados devolucionproductosterminados) {
       this.detalleventa = detalleventa;
       this.devolucionproductosterminados = devolucionproductosterminados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Detalleventa getDetalleventa() {
        return this.detalleventa;
    }
    
    public void setDetalleventa(Detalleventa detalleventa) {
        this.detalleventa = detalleventa;
    }
    public Devolucionproductosterminados getDevolucionproductosterminados() {
        return this.devolucionproductosterminados;
    }
    
    public void setDevolucionproductosterminados(Devolucionproductosterminados devolucionproductosterminados) {
        this.devolucionproductosterminados = devolucionproductosterminados;
    }




}


