package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Detallehojaruta generated by hbm2java
 */
public class Detallehojaruta  implements java.io.Serializable {


     private Integer id;
     private Hojaruta hojaruta;
     private Empresacliente empresacliente;
     private Domicilio domicilio;

    public Detallehojaruta() {
    }

    public Detallehojaruta(Hojaruta hojaruta, Empresacliente empresacliente, Domicilio domicilio) {
       this.hojaruta = hojaruta;
       this.empresacliente = empresacliente;
       this.domicilio = domicilio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hojaruta getHojaruta() {
        return this.hojaruta;
    }
    
    public void setHojaruta(Hojaruta hojaruta) {
        this.hojaruta = hojaruta;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }




}


