package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Detallepedidoproductosterminados generated by hbm2java
 */
public class Detallepedidoproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Productoterminado productoterminado;
     private Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado;
     private Pedidoproductosterminados pedidoproductosterminados;
     private int cantidadProducto;
     private float precioPorUnidad;
     private String motivoDevolucion;
     private String motivoNoEntregado;
     private Integer fechaDevolucion;
     private Set detallefacturas = new HashSet(0);

    public Detallepedidoproductosterminados() {
    }

	
    public Detallepedidoproductosterminados(Productoterminado productoterminado, Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado, Pedidoproductosterminados pedidoproductosterminados, int cantidadProducto, float precioPorUnidad) {
        this.productoterminado = productoterminado;
        this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
        this.pedidoproductosterminados = pedidoproductosterminados;
        this.cantidadProducto = cantidadProducto;
        this.precioPorUnidad = precioPorUnidad;
    }
    public Detallepedidoproductosterminados(Productoterminado productoterminado, Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado, Pedidoproductosterminados pedidoproductosterminados, int cantidadProducto, float precioPorUnidad, String motivoDevolucion, String motivoNoEntregado, Integer fechaDevolucion, Set detallefacturas) {
       this.productoterminado = productoterminado;
       this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
       this.pedidoproductosterminados = pedidoproductosterminados;
       this.cantidadProducto = cantidadProducto;
       this.precioPorUnidad = precioPorUnidad;
       this.motivoDevolucion = motivoDevolucion;
       this.motivoNoEntregado = motivoNoEntregado;
       this.fechaDevolucion = fechaDevolucion;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
    public Estadodetallepedidoproductoterminado getEstadodetallepedidoproductoterminado() {
        return this.estadodetallepedidoproductoterminado;
    }
    
    public void setEstadodetallepedidoproductoterminado(Estadodetallepedidoproductoterminado estadodetallepedidoproductoterminado) {
        this.estadodetallepedidoproductoterminado = estadodetallepedidoproductoterminado;
    }
    public Pedidoproductosterminados getPedidoproductosterminados() {
        return this.pedidoproductosterminados;
    }
    
    public void setPedidoproductosterminados(Pedidoproductosterminados pedidoproductosterminados) {
        this.pedidoproductosterminados = pedidoproductosterminados;
    }
    public int getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(int cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public float getPrecioPorUnidad() {
        return this.precioPorUnidad;
    }
    
    public void setPrecioPorUnidad(float precioPorUnidad) {
        this.precioPorUnidad = precioPorUnidad;
    }
    public String getMotivoDevolucion() {
        return this.motivoDevolucion;
    }
    
    public void setMotivoDevolucion(String motivoDevolucion) {
        this.motivoDevolucion = motivoDevolucion;
    }
    public String getMotivoNoEntregado() {
        return this.motivoNoEntregado;
    }
    
    public void setMotivoNoEntregado(String motivoNoEntregado) {
        this.motivoNoEntregado = motivoNoEntregado;
    }
    public Integer getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Integer fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


