package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleordencompramateriaprima generated by hbm2java
 */
@Entity
@Table(name="detalleordencompramateriaprima"
    ,catalog="seee"
)
public class Detalleordencompramateriaprima  implements java.io.Serializable {


     private int idDetalleOrdenCompra;
     private Materiaprima materiaprima;
     private Detalleordencompra detalleordencompra;
     private int cantidad;
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

    public Detalleordencompramateriaprima() {
    }

	
    public Detalleordencompramateriaprima(int idDetalleOrdenCompra, Materiaprima materiaprima, Detalleordencompra detalleordencompra, int cantidad) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
        this.materiaprima = materiaprima;
        this.detalleordencompra = detalleordencompra;
        this.cantidad = cantidad;
    }
    public Detalleordencompramateriaprima(int idDetalleOrdenCompra, Materiaprima materiaprima, Detalleordencompra detalleordencompra, int cantidad, Set<Detallecompra> detallecompras) {
       this.idDetalleOrdenCompra = idDetalleOrdenCompra;
       this.materiaprima = materiaprima;
       this.detalleordencompra = detalleordencompra;
       this.cantidad = cantidad;
       this.detallecompras = detallecompras;
    }
   
     @Id 
    
    @Column(name="idDetalleOrdenCompra", unique=true, nullable=false)
    public int getIdDetalleOrdenCompra() {
        return this.idDetalleOrdenCompra;
    }
    
    public void setIdDetalleOrdenCompra(int idDetalleOrdenCompra) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idMateriaPrima", nullable=false)
    public Materiaprima getMateriaprima() {
        return this.materiaprima;
    }
    
    public void setMateriaprima(Materiaprima materiaprima) {
        this.materiaprima = materiaprima;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDetalleOrdenCompra", unique=true, nullable=false, insertable=false, updatable=false)
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="detallecompramateriaprima", catalog="seee", joinColumns = { 
        @JoinColumn(name="idDetalleOrdenCompraMateriaPrima", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idDetalleCompra", unique=true, nullable=false, updatable=false) })
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }




}


