package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Detalleordencompramateriaprima generated by hbm2java
 */
public class Detalleordencompramateriaprima  implements java.io.Serializable {


     private int idDetalleOrdenCompra;
     private Materiaprima materiaprima;
     private Detalleordencompra detalleordencompra;
     private int cantidad;
     private Set detallecompras = new HashSet(0);

    public Detalleordencompramateriaprima() {
    }

	
    public Detalleordencompramateriaprima(int idDetalleOrdenCompra, Materiaprima materiaprima, Detalleordencompra detalleordencompra, int cantidad) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
        this.materiaprima = materiaprima;
        this.detalleordencompra = detalleordencompra;
        this.cantidad = cantidad;
    }
    public Detalleordencompramateriaprima(int idDetalleOrdenCompra, Materiaprima materiaprima, Detalleordencompra detalleordencompra, int cantidad, Set detallecompras) {
       this.idDetalleOrdenCompra = idDetalleOrdenCompra;
       this.materiaprima = materiaprima;
       this.detalleordencompra = detalleordencompra;
       this.cantidad = cantidad;
       this.detallecompras = detallecompras;
    }
   
    public int getIdDetalleOrdenCompra() {
        return this.idDetalleOrdenCompra;
    }
    
    public void setIdDetalleOrdenCompra(int idDetalleOrdenCompra) {
        this.idDetalleOrdenCompra = idDetalleOrdenCompra;
    }
    public Materiaprima getMateriaprima() {
        return this.materiaprima;
    }
    
    public void setMateriaprima(Materiaprima materiaprima) {
        this.materiaprima = materiaprima;
    }
    public Detalleordencompra getDetalleordencompra() {
        return this.detalleordencompra;
    }
    
    public void setDetalleordencompra(Detalleordencompra detalleordencompra) {
        this.detalleordencompra = detalleordencompra;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


