package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Detallemateriaprima generated by hbm2java
 */
public class Detallemateriaprima  implements java.io.Serializable {


     private Integer id;
     private Lote lote;
     private Materiaprima materiaprima;
     private int cantidadMateriaPrima;

    public Detallemateriaprima() {
    }

    public Detallemateriaprima(Lote lote, Materiaprima materiaprima, int cantidadMateriaPrima) {
       this.lote = lote;
       this.materiaprima = materiaprima;
       this.cantidadMateriaPrima = cantidadMateriaPrima;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lote getLote() {
        return this.lote;
    }
    
    public void setLote(Lote lote) {
        this.lote = lote;
    }
    public Materiaprima getMateriaprima() {
        return this.materiaprima;
    }
    
    public void setMateriaprima(Materiaprima materiaprima) {
        this.materiaprima = materiaprima;
    }
    public int getCantidadMateriaPrima() {
        return this.cantidadMateriaPrima;
    }
    
    public void setCantidadMateriaPrima(int cantidadMateriaPrima) {
        this.cantidadMateriaPrima = cantidadMateriaPrima;
    }




}


