package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallehojaruta generated by hbm2java
 */
@Entity
@Table(name="detallehojaruta"
    ,catalog="seee"
)
public class Detallehojaruta  implements java.io.Serializable {


     private Integer id;
     private Hojaruta hojaruta;
     private Empresacliente empresacliente;
     private Domicilio domicilio;

    public Detallehojaruta() {
    }

    public Detallehojaruta(Hojaruta hojaruta, Empresacliente empresacliente, Domicilio domicilio) {
       this.hojaruta = hojaruta;
       this.empresacliente = empresacliente;
       this.domicilio = domicilio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHojaRuta", nullable=false)
    public Hojaruta getHojaruta() {
        return this.hojaruta;
    }
    
    public void setHojaruta(Hojaruta hojaruta) {
        this.hojaruta = hojaruta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpresaCliente", nullable=false)
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDomicilioVisitar", nullable=false)
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }




}


