package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallecartera generated by hbm2java
 */
@Entity
@Table(name="detallecartera"
    ,catalog="seee"
)
public class Detallecartera  implements java.io.Serializable {


     private Integer id;
     private Empresacliente empresacliente;
     private Estadocartera estadocartera;
     private Date fechaDesde;
     private Date fechaHasta;
     private Set<Viajante> viajantes = new HashSet<Viajante>(0);

    public Detallecartera() {
    }

	
    public Detallecartera(Empresacliente empresacliente, Estadocartera estadocartera, Date fechaDesde) {
        this.empresacliente = empresacliente;
        this.estadocartera = estadocartera;
        this.fechaDesde = fechaDesde;
    }
    public Detallecartera(Empresacliente empresacliente, Estadocartera estadocartera, Date fechaDesde, Date fechaHasta, Set<Viajante> viajantes) {
       this.empresacliente = empresacliente;
       this.estadocartera = estadocartera;
       this.fechaDesde = fechaDesde;
       this.fechaHasta = fechaHasta;
       this.viajantes = viajantes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpresaCliente", nullable=false)
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoCartera", nullable=false)
    public Estadocartera getEstadocartera() {
        return this.estadocartera;
    }
    
    public void setEstadocartera(Estadocartera estadocartera) {
        this.estadocartera = estadocartera;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaDesde", nullable=false, length=10)
    public Date getFechaDesde() {
        return this.fechaDesde;
    }
    
    public void setFechaDesde(Date fechaDesde) {
        this.fechaDesde = fechaDesde;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaHasta", length=10)
    public Date getFechaHasta() {
        return this.fechaHasta;
    }
    
    public void setFechaHasta(Date fechaHasta) {
        this.fechaHasta = fechaHasta;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="detallecartera")
    public Set<Viajante> getViajantes() {
        return this.viajantes;
    }
    
    public void setViajantes(Set<Viajante> viajantes) {
        this.viajantes = viajantes;
    }




}


