package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Divisa generated by hbm2java
 */
@Entity
@Table(name="divisa"
    ,catalog="seee"
)
public class Divisa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private float tasaCambio;

    public Divisa() {
    }

    public Divisa(String nombre, float tasaCambio) {
       this.nombre = nombre;
       this.tasaCambio = tasaCambio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="tasaCambio", nullable=false, precision=9)
    public float getTasaCambio() {
        return this.tasaCambio;
    }
    
    public void setTasaCambio(float tasaCambio) {
        this.tasaCambio = tasaCambio;
    }




}


