package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Divisa generated by hbm2java
 */
public class Divisa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private float tasaCambio;

    public Divisa() {
    }

    public Divisa(String nombre, float tasaCambio) {
       this.nombre = nombre;
       this.tasaCambio = tasaCambio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getTasaCambio() {
        return this.tasaCambio;
    }
    
    public void setTasaCambio(float tasaCambio) {
        this.tasaCambio = tasaCambio;
    }




}


