package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name="domicilio"
    ,catalog="seee"
)
public class Domicilio  implements java.io.Serializable {


     private Integer id;
     private Barrio barrio;
     private Integer altura;
     private String nombreCalle;
     private Integer nroDpto;
     private Integer codPostal;
     private Set<Empresacliente> empresaclientes = new HashSet<Empresacliente>(0);
     private Set<Empresatransporte> empresatransportes = new HashSet<Empresatransporte>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Hojaruta> hojarutas = new HashSet<Hojaruta>(0);
     private Set<Detallehojaruta> detallehojarutas = new HashSet<Detallehojaruta>(0);

    public Domicilio() {
    }

	
    public Domicilio(Barrio barrio) {
        this.barrio = barrio;
    }
    public Domicilio(Barrio barrio, Integer altura, String nombreCalle, Integer nroDpto, Integer codPostal, Set<Empresacliente> empresaclientes, Set<Empresatransporte> empresatransportes, Set<Persona> personas, Set<Proveedor> proveedors, Set<Hojaruta> hojarutas, Set<Detallehojaruta> detallehojarutas) {
       this.barrio = barrio;
       this.altura = altura;
       this.nombreCalle = nombreCalle;
       this.nroDpto = nroDpto;
       this.codPostal = codPostal;
       this.empresaclientes = empresaclientes;
       this.empresatransportes = empresatransportes;
       this.personas = personas;
       this.proveedors = proveedors;
       this.hojarutas = hojarutas;
       this.detallehojarutas = detallehojarutas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBarrio", nullable=false)
    public Barrio getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(Barrio barrio) {
        this.barrio = barrio;
    }
    
    @Column(name="altura")
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }
    
    @Column(name="nombreCalle", length=20)
    public String getNombreCalle() {
        return this.nombreCalle;
    }
    
    public void setNombreCalle(String nombreCalle) {
        this.nombreCalle = nombreCalle;
    }
    
    @Column(name="nroDpto")
    public Integer getNroDpto() {
        return this.nroDpto;
    }
    
    public void setNroDpto(Integer nroDpto) {
        this.nroDpto = nroDpto;
    }
    
    @Column(name="codPostal")
    public Integer getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Empresacliente> getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set<Empresacliente> empresaclientes) {
        this.empresaclientes = empresaclientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Empresatransporte> getEmpresatransportes() {
        return this.empresatransportes;
    }
    
    public void setEmpresatransportes(Set<Empresatransporte> empresatransportes) {
        this.empresatransportes = empresatransportes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Hojaruta> getHojarutas() {
        return this.hojarutas;
    }
    
    public void setHojarutas(Set<Hojaruta> hojarutas) {
        this.hojarutas = hojarutas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="domicilio")
    public Set<Detallehojaruta> getDetallehojarutas() {
        return this.detallehojarutas;
    }
    
    public void setDetallehojarutas(Set<Detallehojaruta> detallehojarutas) {
        this.detallehojarutas = detallehojarutas;
    }




}


