package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private Integer id;
     private Barrio barrio;
     private Integer altura;
     private String nombreCalle;
     private Integer nroDpto;
     private Integer codPostal;
     private Set empresaclientes = new HashSet(0);
     private Set empresatransportes = new HashSet(0);
     private Set personas = new HashSet(0);
     private Set proveedors = new HashSet(0);
     private Set hojarutas = new HashSet(0);
     private Set detallehojarutas = new HashSet(0);

    public Domicilio() {
    }

	
    public Domicilio(Barrio barrio) {
        this.barrio = barrio;
    }
    public Domicilio(Barrio barrio, Integer altura, String nombreCalle, Integer nroDpto, Integer codPostal, Set empresaclientes, Set empresatransportes, Set personas, Set proveedors, Set hojarutas, Set detallehojarutas) {
       this.barrio = barrio;
       this.altura = altura;
       this.nombreCalle = nombreCalle;
       this.nroDpto = nroDpto;
       this.codPostal = codPostal;
       this.empresaclientes = empresaclientes;
       this.empresatransportes = empresatransportes;
       this.personas = personas;
       this.proveedors = proveedors;
       this.hojarutas = hojarutas;
       this.detallehojarutas = detallehojarutas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Barrio getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(Barrio barrio) {
        this.barrio = barrio;
    }
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }
    public String getNombreCalle() {
        return this.nombreCalle;
    }
    
    public void setNombreCalle(String nombreCalle) {
        this.nombreCalle = nombreCalle;
    }
    public Integer getNroDpto() {
        return this.nroDpto;
    }
    
    public void setNroDpto(Integer nroDpto) {
        this.nroDpto = nroDpto;
    }
    public Integer getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }
    public Set getEmpresaclientes() {
        return this.empresaclientes;
    }
    
    public void setEmpresaclientes(Set empresaclientes) {
        this.empresaclientes = empresaclientes;
    }
    public Set getEmpresatransportes() {
        return this.empresatransportes;
    }
    
    public void setEmpresatransportes(Set empresatransportes) {
        this.empresatransportes = empresatransportes;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }
    public Set getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set proveedors) {
        this.proveedors = proveedors;
    }
    public Set getHojarutas() {
        return this.hojarutas;
    }
    
    public void setHojarutas(Set hojarutas) {
        this.hojarutas = hojarutas;
    }
    public Set getDetallehojarutas() {
        return this.detallehojarutas;
    }
    
    public void setDetallehojarutas(Set detallehojarutas) {
        this.detallehojarutas = detallehojarutas;
    }




}


