package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Empresaclientexpersona generated by hbm2java
 */
public class Empresaclientexpersona  implements java.io.Serializable {


     private Integer id;
     private Empresacliente empresacliente;
     private Persona persona;

    public Empresaclientexpersona() {
    }

    public Empresaclientexpersona(Empresacliente empresacliente, Persona persona) {
       this.empresacliente = empresacliente;
       this.persona = persona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }




}


