package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresatransporte generated by hbm2java
 */
@Entity
@Table(name="empresatransporte"
    ,catalog="seee"
)
public class Empresatransporte  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private String nombre;
     private Set<Ordencompra> ordencomprasForIdEmpresaTransporteInterior = new HashSet<Ordencompra>(0);
     private Set<Ordencompra> ordencomprasForIdEmpresaTransporteExterior = new HashSet<Ordencompra>(0);

    public Empresatransporte() {
    }

	
    public Empresatransporte(String nombre) {
        this.nombre = nombre;
    }
    public Empresatransporte(Domicilio domicilio, String nombre, Set<Ordencompra> ordencomprasForIdEmpresaTransporteInterior, Set<Ordencompra> ordencomprasForIdEmpresaTransporteExterior) {
       this.domicilio = domicilio;
       this.nombre = nombre;
       this.ordencomprasForIdEmpresaTransporteInterior = ordencomprasForIdEmpresaTransporteInterior;
       this.ordencomprasForIdEmpresaTransporteExterior = ordencomprasForIdEmpresaTransporteExterior;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDomicilio")
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empresatransporteByIdEmpresaTransporteInterior")
    public Set<Ordencompra> getOrdencomprasForIdEmpresaTransporteInterior() {
        return this.ordencomprasForIdEmpresaTransporteInterior;
    }
    
    public void setOrdencomprasForIdEmpresaTransporteInterior(Set<Ordencompra> ordencomprasForIdEmpresaTransporteInterior) {
        this.ordencomprasForIdEmpresaTransporteInterior = ordencomprasForIdEmpresaTransporteInterior;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empresatransporteByIdEmpresaTransporteExterior")
    public Set<Ordencompra> getOrdencomprasForIdEmpresaTransporteExterior() {
        return this.ordencomprasForIdEmpresaTransporteExterior;
    }
    
    public void setOrdencomprasForIdEmpresaTransporteExterior(Set<Ordencompra> ordencomprasForIdEmpresaTransporteExterior) {
        this.ordencomprasForIdEmpresaTransporteExterior = ordencomprasForIdEmpresaTransporteExterior;
    }




}


