package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresatransporte generated by hbm2java
 */
public class Empresatransporte  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private String nombre;
     private Set ordencomprasForIdEmpresaTransporteInterior = new HashSet(0);
     private Set ordencomprasForIdEmpresaTransporteExterior = new HashSet(0);

    public Empresatransporte() {
    }

	
    public Empresatransporte(String nombre) {
        this.nombre = nombre;
    }
    public Empresatransporte(Domicilio domicilio, String nombre, Set ordencomprasForIdEmpresaTransporteInterior, Set ordencomprasForIdEmpresaTransporteExterior) {
       this.domicilio = domicilio;
       this.nombre = nombre;
       this.ordencomprasForIdEmpresaTransporteInterior = ordencomprasForIdEmpresaTransporteInterior;
       this.ordencomprasForIdEmpresaTransporteExterior = ordencomprasForIdEmpresaTransporteExterior;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdencomprasForIdEmpresaTransporteInterior() {
        return this.ordencomprasForIdEmpresaTransporteInterior;
    }
    
    public void setOrdencomprasForIdEmpresaTransporteInterior(Set ordencomprasForIdEmpresaTransporteInterior) {
        this.ordencomprasForIdEmpresaTransporteInterior = ordencomprasForIdEmpresaTransporteInterior;
    }
    public Set getOrdencomprasForIdEmpresaTransporteExterior() {
        return this.ordencomprasForIdEmpresaTransporteExterior;
    }
    
    public void setOrdencomprasForIdEmpresaTransporteExterior(Set ordencomprasForIdEmpresaTransporteExterior) {
        this.ordencomprasForIdEmpresaTransporteExterior = ordencomprasForIdEmpresaTransporteExterior;
    }




}


