package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadodetalleordencompra generated by hbm2java
 */
public class Estadodetalleordencompra  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set detalleordencompras = new HashSet(0);

    public Estadodetalleordencompra() {
    }

	
    public Estadodetalleordencompra(String nombre) {
        this.nombre = nombre;
    }
    public Estadodetalleordencompra(String nombre, Set detalleordencompras) {
       this.nombre = nombre;
       this.detalleordencompras = detalleordencompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDetalleordencompras() {
        return this.detalleordencompras;
    }
    
    public void setDetalleordencompras(Set detalleordencompras) {
        this.detalleordencompras = detalleordencompras;
    }




}


