package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadocobrocheque generated by hbm2java
 */
@Entity
@Table(name="estadocobrocheque"
    ,catalog="seee"
)
public class Estadocobrocheque  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Cobrocheque> cobrocheques = new HashSet<Cobrocheque>(0);

    public Estadocobrocheque() {
    }

	
    public Estadocobrocheque(String nombre) {
        this.nombre = nombre;
    }
    public Estadocobrocheque(String nombre, Set<Cobrocheque> cobrocheques) {
       this.nombre = nombre;
       this.cobrocheques = cobrocheques;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadocobrocheque")
    public Set<Cobrocheque> getCobrocheques() {
        return this.cobrocheques;
    }
    
    public void setCobrocheques(Set<Cobrocheque> cobrocheques) {
        this.cobrocheques = cobrocheques;
    }




}


