package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadoordencompra generated by hbm2java
 */
public class Estadoordencompra  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set ordencompras = new HashSet(0);

    public Estadoordencompra() {
    }

	
    public Estadoordencompra(String nombre) {
        this.nombre = nombre;
    }
    public Estadoordencompra(String nombre, Set ordencompras) {
       this.nombre = nombre;
       this.ordencompras = ordencompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set ordencompras) {
        this.ordencompras = ordencompras;
    }




}


