package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadonotificacionreaprovisionamiento generated by hbm2java
 */
@Entity
@Table(name="estadonotificacionreaprovisionamiento"
    ,catalog="seee"
)
public class Estadonotificacionreaprovisionamiento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Notificacionreaprovisionamiento> notificacionreaprovisionamientos = new HashSet<Notificacionreaprovisionamiento>(0);

    public Estadonotificacionreaprovisionamiento() {
    }

	
    public Estadonotificacionreaprovisionamiento(String nombre) {
        this.nombre = nombre;
    }
    public Estadonotificacionreaprovisionamiento(String nombre, Set<Notificacionreaprovisionamiento> notificacionreaprovisionamientos) {
       this.nombre = nombre;
       this.notificacionreaprovisionamientos = notificacionreaprovisionamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadonotificacionreaprovisionamiento")
    public Set<Notificacionreaprovisionamiento> getNotificacionreaprovisionamientos() {
        return this.notificacionreaprovisionamientos;
    }
    
    public void setNotificacionreaprovisionamientos(Set<Notificacionreaprovisionamiento> notificacionreaprovisionamientos) {
        this.notificacionreaprovisionamientos = notificacionreaprovisionamientos;
    }




}


