package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadopedidoproductosterminados generated by hbm2java
 */
public class Estadopedidoproductosterminados  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set pedidoproductosterminadoses = new HashSet(0);

    public Estadopedidoproductosterminados() {
    }

	
    public Estadopedidoproductosterminados(String nombre) {
        this.nombre = nombre;
    }
    public Estadopedidoproductosterminados(String nombre, Set pedidoproductosterminadoses) {
       this.nombre = nombre;
       this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidoproductosterminadoses() {
        return this.pedidoproductosterminadoses;
    }
    
    public void setPedidoproductosterminadoses(Set pedidoproductosterminadoses) {
        this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }




}


