package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadodetallepedidoproductoterminado generated by hbm2java
 */
public class Estadodetallepedidoproductoterminado  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set detallepedidoproductosterminadoses = new HashSet(0);

    public Estadodetallepedidoproductoterminado() {
    }

	
    public Estadodetallepedidoproductoterminado(String nombre) {
        this.nombre = nombre;
    }
    public Estadodetallepedidoproductoterminado(String nombre, Set detallepedidoproductosterminadoses) {
       this.nombre = nombre;
       this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDetallepedidoproductosterminadoses() {
        return this.detallepedidoproductosterminadoses;
    }
    
    public void setDetallepedidoproductosterminadoses(Set detallepedidoproductosterminadoses) {
        this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
    }




}


