package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadoventa generated by hbm2java
 */
public class Estadoventa  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set ventas = new HashSet(0);

    public Estadoventa() {
    }

	
    public Estadoventa(String nombre) {
        this.nombre = nombre;
    }
    public Estadoventa(String nombre, Set ventas) {
       this.nombre = nombre;
       this.ventas = ventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


