package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadopedidoproductosterminados generated by hbm2java
 */
@Entity
@Table(name="estadopedidoproductosterminados"
    ,catalog="seee"
)
public class Estadopedidoproductosterminados  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Pedidoproductosterminados> pedidoproductosterminadoses = new HashSet<Pedidoproductosterminados>(0);

    public Estadopedidoproductosterminados() {
    }

	
    public Estadopedidoproductosterminados(String nombre) {
        this.nombre = nombre;
    }
    public Estadopedidoproductosterminados(String nombre, Set<Pedidoproductosterminados> pedidoproductosterminadoses) {
       this.nombre = nombre;
       this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadopedidoproductosterminados")
    public Set<Pedidoproductosterminados> getPedidoproductosterminadoses() {
        return this.pedidoproductosterminadoses;
    }
    
    public void setPedidoproductosterminadoses(Set<Pedidoproductosterminados> pedidoproductosterminadoses) {
        this.pedidoproductosterminadoses = pedidoproductosterminadoses;
    }




}


