package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hojaruta generated by hbm2java
 */
public class Hojaruta  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private Date fecha;
     private Set detallehojarutas = new HashSet(0);

    public Hojaruta() {
    }

	
    public Hojaruta(Domicilio domicilio, Date fecha) {
        this.domicilio = domicilio;
        this.fecha = fecha;
    }
    public Hojaruta(Domicilio domicilio, Date fecha, Set detallehojarutas) {
       this.domicilio = domicilio;
       this.fecha = fecha;
       this.detallehojarutas = detallehojarutas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallehojarutas() {
        return this.detallehojarutas;
    }
    
    public void setDetallehojarutas(Set detallehojarutas) {
        this.detallehojarutas = detallehojarutas;
    }




}


