package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Materiaprima generated by hbm2java
 */
public class Materiaprima  implements java.io.Serializable {


     private Integer id;
     private int codigo;
     private String nombre;
     private String descripcion;
     private int stockActual;
     private Set detallemateriaprimas = new HashSet(0);
     private Set detalleordencompramateriaprimas = new HashSet(0);

    public Materiaprima() {
    }

	
    public Materiaprima(int codigo, String nombre, int stockActual) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.stockActual = stockActual;
    }
    public Materiaprima(int codigo, String nombre, String descripcion, int stockActual, Set detallemateriaprimas, Set detalleordencompramateriaprimas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stockActual = stockActual;
       this.detallemateriaprimas = detallemateriaprimas;
       this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(int stockActual) {
        this.stockActual = stockActual;
    }
    public Set getDetallemateriaprimas() {
        return this.detallemateriaprimas;
    }
    
    public void setDetallemateriaprimas(Set detallemateriaprimas) {
        this.detallemateriaprimas = detallemateriaprimas;
    }
    public Set getDetalleordencompramateriaprimas() {
        return this.detalleordencompramateriaprimas;
    }
    
    public void setDetalleordencompramateriaprimas(Set detalleordencompramateriaprimas) {
        this.detalleordencompramateriaprimas = detalleordencompramateriaprimas;
    }




}


