package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notificacionreaprovisionamiento generated by hbm2java
 */
@Entity
@Table(name="notificacionreaprovisionamiento"
    ,catalog="seee"
)
public class Notificacionreaprovisionamiento  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento;
     private Date fechaIngresoDeposito;
     private Set<Detallenotificacionreaprovisionamiento> detallenotificacionreaprovisionamientos = new HashSet<Detallenotificacionreaprovisionamiento>(0);

    public Notificacionreaprovisionamiento() {
    }

	
    public Notificacionreaprovisionamiento(Empleado empleado, Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento, Date fechaIngresoDeposito) {
        this.empleado = empleado;
        this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
        this.fechaIngresoDeposito = fechaIngresoDeposito;
    }
    public Notificacionreaprovisionamiento(Empleado empleado, Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento, Date fechaIngresoDeposito, Set<Detallenotificacionreaprovisionamiento> detallenotificacionreaprovisionamientos) {
       this.empleado = empleado;
       this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
       this.fechaIngresoDeposito = fechaIngresoDeposito;
       this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoNotificacionReaprovisionamiento", nullable=false)
    public Estadonotificacionreaprovisionamiento getEstadonotificacionreaprovisionamiento() {
        return this.estadonotificacionreaprovisionamiento;
    }
    
    public void setEstadonotificacionreaprovisionamiento(Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento) {
        this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaIngresoDeposito", nullable=false, length=10)
    public Date getFechaIngresoDeposito() {
        return this.fechaIngresoDeposito;
    }
    
    public void setFechaIngresoDeposito(Date fechaIngresoDeposito) {
        this.fechaIngresoDeposito = fechaIngresoDeposito;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="notificacionreaprovisionamiento")
    public Set<Detallenotificacionreaprovisionamiento> getDetallenotificacionreaprovisionamientos() {
        return this.detallenotificacionreaprovisionamientos;
    }
    
    public void setDetallenotificacionreaprovisionamientos(Set<Detallenotificacionreaprovisionamiento> detallenotificacionreaprovisionamientos) {
        this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
    }




}


