package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notificacionreaprovisionamiento generated by hbm2java
 */
public class Notificacionreaprovisionamiento  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento;
     private Date fechaIngresoDeposito;
     private Set detallenotificacionreaprovisionamientos = new HashSet(0);

    public Notificacionreaprovisionamiento() {
    }

	
    public Notificacionreaprovisionamiento(Empleado empleado, Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento, Date fechaIngresoDeposito) {
        this.empleado = empleado;
        this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
        this.fechaIngresoDeposito = fechaIngresoDeposito;
    }
    public Notificacionreaprovisionamiento(Empleado empleado, Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento, Date fechaIngresoDeposito, Set detallenotificacionreaprovisionamientos) {
       this.empleado = empleado;
       this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
       this.fechaIngresoDeposito = fechaIngresoDeposito;
       this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Estadonotificacionreaprovisionamiento getEstadonotificacionreaprovisionamiento() {
        return this.estadonotificacionreaprovisionamiento;
    }
    
    public void setEstadonotificacionreaprovisionamiento(Estadonotificacionreaprovisionamiento estadonotificacionreaprovisionamiento) {
        this.estadonotificacionreaprovisionamiento = estadonotificacionreaprovisionamiento;
    }
    public Date getFechaIngresoDeposito() {
        return this.fechaIngresoDeposito;
    }
    
    public void setFechaIngresoDeposito(Date fechaIngresoDeposito) {
        this.fechaIngresoDeposito = fechaIngresoDeposito;
    }
    public Set getDetallenotificacionreaprovisionamientos() {
        return this.detallenotificacionreaprovisionamientos;
    }
    
    public void setDetallenotificacionreaprovisionamientos(Set detallenotificacionreaprovisionamientos) {
        this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
    }




}


