package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Ordencompraximportacion generated by hbm2java
 */
public class Ordencompraximportacion  implements java.io.Serializable {


     private Integer id;
     private Importacion importacion;
     private Ordencompra ordencompra;

    public Ordencompraximportacion() {
    }

    public Ordencompraximportacion(Importacion importacion, Ordencompra ordencompra) {
       this.importacion = importacion;
       this.ordencompra = ordencompra;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Importacion getImportacion() {
        return this.importacion;
    }
    
    public void setImportacion(Importacion importacion) {
        this.importacion = importacion;
    }
    public Ordencompra getOrdencompra() {
        return this.ordencompra;
    }
    
    public void setOrdencompra(Ordencompra ordencompra) {
        this.ordencompra = ordencompra;
    }




}


