package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Otrosgastos generated by hbm2java
 */
@Entity
@Table(name="otrosgastos"
    ,catalog="seee"
)
public class Otrosgastos  implements java.io.Serializable {


     private int idPago;
     private Pago pago;
     private String descripcion;

    public Otrosgastos() {
    }

    public Otrosgastos(int idPago, Pago pago, String descripcion) {
       this.idPago = idPago;
       this.pago = pago;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="idPago", unique=true, nullable=false)
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPago", unique=true, nullable=false, insertable=false, updatable=false)
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    
    @Column(name="descripcion", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


