package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA



/**
 * Otrosgastos generated by hbm2java
 */
public class Otrosgastos  implements java.io.Serializable {


     private int idPago;
     private Pago pago;
     private String descripcion;

    public Otrosgastos() {
    }

    public Otrosgastos(int idPago, Pago pago, String descripcion) {
       this.idPago = idPago;
       this.pago = pago;
       this.descripcion = descripcion;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


