package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name="pago"
    ,catalog="seee"
)
public class Pago  implements java.io.Serializable {


     private Integer id;
     private float monto;
     private Date fechaPago;
     private int nroPago;
     private Integer idDivisa;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Ordencompra> ordencompras = new HashSet<Ordencompra>(0);
     private Set<Otrosgastos> otrosgastoses = new HashSet<Otrosgastos>(0);

    public Pago() {
    }

	
    public Pago(float monto, Date fechaPago, int nroPago) {
        this.monto = monto;
        this.fechaPago = fechaPago;
        this.nroPago = nroPago;
    }
    public Pago(float monto, Date fechaPago, int nroPago, Integer idDivisa, Set<Empleado> empleados, Set<Ordencompra> ordencompras, Set<Otrosgastos> otrosgastoses) {
       this.monto = monto;
       this.fechaPago = fechaPago;
       this.nroPago = nroPago;
       this.idDivisa = idDivisa;
       this.empleados = empleados;
       this.ordencompras = ordencompras;
       this.otrosgastoses = otrosgastoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="monto", nullable=false, precision=9, scale=3)
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaPago", nullable=false, length=10)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    
    @Column(name="nroPago", nullable=false)
    public int getNroPago() {
        return this.nroPago;
    }
    
    public void setNroPago(int nroPago) {
        this.nroPago = nroPago;
    }
    
    @Column(name="idDivisa")
    public Integer getIdDivisa() {
        return this.idDivisa;
    }
    
    public void setIdDivisa(Integer idDivisa) {
        this.idDivisa = idDivisa;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="pagoempleado", catalog="seee", joinColumns = { 
        @JoinColumn(name="idPago", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idEmpleado", nullable=false, updatable=false) })
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="pagoproveedor", catalog="seee", joinColumns = { 
        @JoinColumn(name="idPago", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idOrdenCompra", nullable=false, updatable=false) })
    public Set<Ordencompra> getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set<Ordencompra> ordencompras) {
        this.ordencompras = ordencompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pago")
    public Set<Otrosgastos> getOtrosgastoses() {
        return this.otrosgastoses;
    }
    
    public void setOtrosgastoses(Set<Otrosgastos> otrosgastoses) {
        this.otrosgastoses = otrosgastoses;
    }




}


