package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer id;
     private float monto;
     private Date fechaPago;
     private int nroPago;
     private Integer idDivisa;
     private Set empleados = new HashSet(0);
     private Set ordencompras = new HashSet(0);
     private Set otrosgastoses = new HashSet(0);

    public Pago() {
    }

	
    public Pago(float monto, Date fechaPago, int nroPago) {
        this.monto = monto;
        this.fechaPago = fechaPago;
        this.nroPago = nroPago;
    }
    public Pago(float monto, Date fechaPago, int nroPago, Integer idDivisa, Set empleados, Set ordencompras, Set otrosgastoses) {
       this.monto = monto;
       this.fechaPago = fechaPago;
       this.nroPago = nroPago;
       this.idDivisa = idDivisa;
       this.empleados = empleados;
       this.ordencompras = ordencompras;
       this.otrosgastoses = otrosgastoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public float getMonto() {
        return this.monto;
    }
    
    public void setMonto(float monto) {
        this.monto = monto;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public int getNroPago() {
        return this.nroPago;
    }
    
    public void setNroPago(int nroPago) {
        this.nroPago = nroPago;
    }
    public Integer getIdDivisa() {
        return this.idDivisa;
    }
    
    public void setIdDivisa(Integer idDivisa) {
        this.idDivisa = idDivisa;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getOrdencompras() {
        return this.ordencompras;
    }
    
    public void setOrdencompras(Set ordencompras) {
        this.ordencompras = ordencompras;
    }
    public Set getOtrosgastoses() {
        return this.otrosgastoses;
    }
    
    public void setOtrosgastoses(Set otrosgastoses) {
        this.otrosgastoses = otrosgastoses;
    }




}


