package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidoproductosterminados generated by hbm2java
 */
public class Pedidoproductosterminados  implements java.io.Serializable {


     private Integer id;
     private Empleado empleado;
     private Empresacliente empresacliente;
     private Estadopedidoproductosterminados estadopedidoproductosterminados;
     private Viajante viajante;
     private Date fechaPedido;
     private Date fechaCancelacion;
     private String motivoEstado;
     private Date fechaEstimadaEntrega;
     private Date fechaEntregaViajante;
     private Float descuento;
     private String domicilioEnvio;
     private Set ventas = new HashSet(0);
     private Set detallepedidoproductosterminadoses = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Pedidoproductosterminados() {
    }

	
    public Pedidoproductosterminados(Empleado empleado, Empresacliente empresacliente, Estadopedidoproductosterminados estadopedidoproductosterminados, Viajante viajante, Date fechaPedido) {
        this.empleado = empleado;
        this.empresacliente = empresacliente;
        this.estadopedidoproductosterminados = estadopedidoproductosterminados;
        this.viajante = viajante;
        this.fechaPedido = fechaPedido;
    }
    public Pedidoproductosterminados(Empleado empleado, Empresacliente empresacliente, Estadopedidoproductosterminados estadopedidoproductosterminados, Viajante viajante, Date fechaPedido, Date fechaCancelacion, String motivoEstado, Date fechaEstimadaEntrega, Date fechaEntregaViajante, Float descuento, String domicilioEnvio, Set ventas, Set detallepedidoproductosterminadoses, Set facturas) {
       this.empleado = empleado;
       this.empresacliente = empresacliente;
       this.estadopedidoproductosterminados = estadopedidoproductosterminados;
       this.viajante = viajante;
       this.fechaPedido = fechaPedido;
       this.fechaCancelacion = fechaCancelacion;
       this.motivoEstado = motivoEstado;
       this.fechaEstimadaEntrega = fechaEstimadaEntrega;
       this.fechaEntregaViajante = fechaEntregaViajante;
       this.descuento = descuento;
       this.domicilioEnvio = domicilioEnvio;
       this.ventas = ventas;
       this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
       this.facturas = facturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Estadopedidoproductosterminados getEstadopedidoproductosterminados() {
        return this.estadopedidoproductosterminados;
    }
    
    public void setEstadopedidoproductosterminados(Estadopedidoproductosterminados estadopedidoproductosterminados) {
        this.estadopedidoproductosterminados = estadopedidoproductosterminados;
    }
    public Viajante getViajante() {
        return this.viajante;
    }
    
    public void setViajante(Viajante viajante) {
        this.viajante = viajante;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    public String getMotivoEstado() {
        return this.motivoEstado;
    }
    
    public void setMotivoEstado(String motivoEstado) {
        this.motivoEstado = motivoEstado;
    }
    public Date getFechaEstimadaEntrega() {
        return this.fechaEstimadaEntrega;
    }
    
    public void setFechaEstimadaEntrega(Date fechaEstimadaEntrega) {
        this.fechaEstimadaEntrega = fechaEstimadaEntrega;
    }
    public Date getFechaEntregaViajante() {
        return this.fechaEntregaViajante;
    }
    
    public void setFechaEntregaViajante(Date fechaEntregaViajante) {
        this.fechaEntregaViajante = fechaEntregaViajante;
    }
    public Float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Float descuento) {
        this.descuento = descuento;
    }
    public String getDomicilioEnvio() {
        return this.domicilioEnvio;
    }
    
    public void setDomicilioEnvio(String domicilioEnvio) {
        this.domicilioEnvio = domicilioEnvio;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getDetallepedidoproductosterminadoses() {
        return this.detallepedidoproductosterminadoses;
    }
    
    public void setDetallepedidoproductosterminadoses(Set detallepedidoproductosterminadoses) {
        this.detallepedidoproductosterminadoses = detallepedidoproductosterminadoses;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


