package model;
// Generated 07-jun-2010 1:17:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="seee"
)
public class Persona  implements java.io.Serializable {


     private Integer id;
     private Domicilio domicilio;
     private Tipodni tipodni;
     private String nombre;
     private String apellido;
     private String telefono;
     private String celular;
     private String dni;
     private String mail;
     private Set<Viajante> viajantes = new HashSet<Viajante>(0);
     private Set<Empresaclientexpersona> empresaclientexpersonas = new HashSet<Empresaclientexpersona>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Persona() {
    }

	
    public Persona(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Persona(Domicilio domicilio, Tipodni tipodni, String nombre, String apellido, String telefono, String celular, String dni, String mail, Set<Viajante> viajantes, Set<Empresaclientexpersona> empresaclientexpersonas, Set<Empleado> empleados) {
       this.domicilio = domicilio;
       this.tipodni = tipodni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.celular = celular;
       this.dni = dni;
       this.mail = mail;
       this.viajantes = viajantes;
       this.empresaclientexpersonas = empresaclientexpersonas;
       this.empleados = empleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDomicilio")
    public Domicilio getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(Domicilio domicilio) {
        this.domicilio = domicilio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoDni")
    public Tipodni getTipodni() {
        return this.tipodni;
    }
    
    public void setTipodni(Tipodni tipodni) {
        this.tipodni = tipodni;
    }
    
    @Column(name="nombre", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellido", nullable=false, length=20)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular", length=20)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    
    @Column(name="dni", length=20)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    
    @Column(name="mail", length=30)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Viajante> getViajantes() {
        return this.viajantes;
    }
    
    public void setViajantes(Set<Viajante> viajantes) {
        this.viajantes = viajantes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Empresaclientexpersona> getEmpresaclientexpersonas() {
        return this.empresaclientexpersonas;
    }
    
    public void setEmpresaclientexpersonas(Set<Empresaclientexpersona> empresaclientexpersonas) {
        this.empresaclientexpersonas = empresaclientexpersonas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


