package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Productoimportado generated by hbm2java
 */
public class Productoimportado  implements java.io.Serializable {


     private int idProductoTerminado;
     private Productoterminado productoterminado;
     private float precioCompra;
     private Set detallenotificacionreaprovisionamientos = new HashSet(0);
     private Set detalleordencompraproductoimportados = new HashSet(0);

    public Productoimportado() {
    }

	
    public Productoimportado(int idProductoTerminado, Productoterminado productoterminado, float precioCompra) {
        this.idProductoTerminado = idProductoTerminado;
        this.productoterminado = productoterminado;
        this.precioCompra = precioCompra;
    }
    public Productoimportado(int idProductoTerminado, Productoterminado productoterminado, float precioCompra, Set detallenotificacionreaprovisionamientos, Set detalleordencompraproductoimportados) {
       this.idProductoTerminado = idProductoTerminado;
       this.productoterminado = productoterminado;
       this.precioCompra = precioCompra;
       this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
       this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }
   
    public int getIdProductoTerminado() {
        return this.idProductoTerminado;
    }
    
    public void setIdProductoTerminado(int idProductoTerminado) {
        this.idProductoTerminado = idProductoTerminado;
    }
    public Productoterminado getProductoterminado() {
        return this.productoterminado;
    }
    
    public void setProductoterminado(Productoterminado productoterminado) {
        this.productoterminado = productoterminado;
    }
    public float getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(float precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Set getDetallenotificacionreaprovisionamientos() {
        return this.detallenotificacionreaprovisionamientos;
    }
    
    public void setDetallenotificacionreaprovisionamientos(Set detallenotificacionreaprovisionamientos) {
        this.detallenotificacionreaprovisionamientos = detallenotificacionreaprovisionamientos;
    }
    public Set getDetalleordencompraproductoimportados() {
        return this.detalleordencompraproductoimportados;
    }
    
    public void setDetalleordencompraproductoimportados(Set detalleordencompraproductoimportados) {
        this.detalleordencompraproductoimportados = detalleordencompraproductoimportados;
    }




}


