package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipofactura generated by hbm2java
 */
public class Tipofactura  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set facturas = new HashSet(0);

    public Tipofactura() {
    }

	
    public Tipofactura(String nombre) {
        this.nombre = nombre;
    }
    public Tipofactura(String nombre, Set facturas) {
       this.nombre = nombre;
       this.facturas = facturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


