package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoaccesorio generated by hbm2java
 */
public class Tipoaccesorio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set accesorios = new HashSet(0);

    public Tipoaccesorio() {
    }

	
    public Tipoaccesorio(String nombre) {
        this.nombre = nombre;
    }
    public Tipoaccesorio(String nombre, Set accesorios) {
       this.nombre = nombre;
       this.accesorios = accesorios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAccesorios() {
        return this.accesorios;
    }
    
    public void setAccesorios(Set accesorios) {
        this.accesorios = accesorios;
    }




}


