package model;
// Generated 07-jun-2010 21:59:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodni generated by hbm2java
 */
public class Tipodni  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set personas = new HashSet(0);

    public Tipodni() {
    }

	
    public Tipodni(String nombre) {
        this.nombre = nombre;
    }
    public Tipodni(String nombre, Set personas) {
       this.nombre = nombre;
       this.personas = personas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


